import { describe, expect, it } from 'vitest'
import fixtureSample from '../../samples/fixture-pack.v1.sample.json'
import researchSample from '../../samples/research-pack.v1.sample.json'
import { analyse, defaultModelSettings, MODEL_VERSION, relationship } from './analysisModel'
import type { FixturePack, ModelSettings, ResearchPack } from './types'

const copies = (count = 3) => {
  const fixture = structuredClone(fixtureSample) as unknown as FixturePack
  const research = structuredClone(researchSample) as unknown as ResearchPack
  const baseFixture = fixture.fixtures[0], baseResearch = research.fixtures[0]
  fixture.fixtures = Array.from({ length: count }, (_, index) => ({ ...structuredClone(baseFixture), fixtureId: `fixture-${index}`, homeTeam: `Home ${index}`, awayTeam: `Away ${index}` }))
  research.fixtures = fixture.fixtures.map((item, index) => ({ ...structuredClone(baseResearch), dataQuality: 'complete', fixtureId: item.fixtureId, homeTeam: item.homeTeam, awayTeam: item.awayTeam, teamNews: { ...baseResearch.teamNews, impact: 'neutral' }, managerialContext: { ...baseResearch.managerialContext, impact: 'neutral' }, homeEvidence: { ...structuredClone(baseResearch.homeEvidence), marketHitRates: baseResearch.homeEvidence.marketHitRates.map(market => ({ ...structuredClone(market), marketKey: `home_result_${index}`, marketGroup: 'match_result', teamSide: 'home', selectionLabel: `${item.homeTeam} win` })) }, awayEvidence: { ...structuredClone(baseResearch.awayEvidence), marketHitRates: baseResearch.awayEvidence.marketHitRates.map(market => ({ ...structuredClone(market), marketKey: `away_score_${index}`, selectionLabel: `${item.awayTeam} to score` })) } }))
  return { fixture, research }
}
const settings = (): ModelSettings => defaultModelSettings('2026-09-01T10:00:00Z', 24)

describe('FormFirst model', () => {
  it('is byte-for-byte deterministic and propagates versions', () => { const { fixture, research } = copies(); const first = analyse(fixture, research, settings()); expect(JSON.stringify(analyse(fixture, research, settings()))).toBe(JSON.stringify(first)); expect(first.modelVersion).toBe(MODEL_VERSION); expect(first.candidates.every(candidate => candidate.fixtureSchemaVersion === '1.0.0' && candidate.researchSchemaVersion === '1.0.0')).toBe(true) })
  it('applies confidence thresholds and whole-percentage scores', () => { const { fixture, research } = copies(1); const strong = analyse(fixture, research, settings()).candidates[0]; expect(Number.isInteger(strong.estimatedProbability)).toBe(true); expect(strong.confidence).toBe('Strong'); research.fixtures[0].homeEvidence.marketHitRates[0].hits = 6; research.fixtures[0].homeEvidence.marketHitRates[0].recentHits = 3; expect(analyse(fixture, research, settings()).candidates.find(x => x.marketGroup === 'match_result')?.confidence).toBe('Good') })
  it('downgrades partial and rejects stale, contradictory, insufficient and material evidence', () => { const { fixture, research } = copies(1); research.fixtures[0].dataQuality = 'partial'; expect(analyse(fixture, research, settings()).candidates[0].confidence).toBe('Moderate'); research.fixtures[0].dataQuality = 'complete'; research.sources[0].retrievedAt = '2026-08-01T00:00:00Z'; expect(analyse(fixture, research, settings()).candidates[0].confidence).toBe('Avoid'); research.sources[0].retrievedAt = '2026-09-01T09:30:00Z'; research.fixtures[0].homeEvidence.marketHitRates[0].hits = 99; expect(analyse(fixture, research, settings()).candidates.find(x => x.marketGroup === 'match_result')?.dataQuality).toBe('contradictory'); research.fixtures[0].homeEvidence.marketHitRates[0].hits = 2; research.fixtures[0].homeEvidence.marketHitRates[0].sampleSize = 2; expect(analyse(fixture, research, settings()).candidates.find(x => x.marketGroup === 'match_result')?.confidence).toBe('Avoid'); research.fixtures[0].teamNews.impact = 'material'; expect(analyse(fixture, research, settings()).candidates.every(x => x.confidence === 'Avoid')).toBe(true) })
  it('excludes unavailable groups and flags unknown availability', () => { const { fixture, research } = copies(1); const unavailable = settings(); unavailable.marketAvailability.match_result = 'unavailable'; expect(analyse(fixture, research, unavailable).candidates.some(x => x.marketGroup === 'match_result')).toBe(false); const candidate = analyse(fixture, research, settings()).candidates[0]; expect(candidate.manualMarketVerificationRequired).toBe(true); expect(candidate.manualMarketVerificationReason).toContain('manual checking') })
  it('rejects duplicates and defined near-duplicates', () => { const { fixture, research } = copies(1); const output = analyse(fixture, research, settings()); const candidate = output.candidates[0]; expect(relationship(candidate, candidate).excluded).toBe(true); const near = { ...candidate, id: `${candidate.id}:variant` }; expect(relationship(candidate, near).excluded).toBe(true) })
  it('penalises same-match combinations and can make a builder fail', () => { const { fixture, research } = copies(1); research.fixtures[0].homeEvidence.marketHitRates[0].hits = 7; research.fixtures[0].homeEvidence.marketHitRates[0].underlyingSupportPercent = 55; research.fixtures[0].awayEvidence.marketHitRates[0].underlyingSupportPercent = 55; const output = analyse(fixture, research, settings()); expect(relationship(output.candidates[0], output.candidates[1]).penalty).toBe(.9); expect(output.builders.highProbability.status).toBe('no_qualifying_builder'); expect(output.builders.highProbability.rejectedCombinations.some(item => item.reason.includes('below 55%'))).toBe(true) })
  it('builds compliant high-probability and balanced builders from all combinations', () => { const { fixture, research } = copies(3); const output = analyse(fixture, research, settings()); expect(output.builders.highProbability.status).toBe('builder'); expect(output.builders.balanced.status).toBe('builder'); if (output.builders.highProbability.status === 'builder') { expect(output.builders.highProbability.selectedLegs.length).toBeGreaterThanOrEqual(2); expect(output.builders.highProbability.selectedLegs.every(x => x.confidence === 'Strong' && x.estimatedProbability >= 72)).toBe(true); expect(output.builders.highProbability.estimatedCombinedProbability).toBeGreaterThanOrEqual(55) } if (output.builders.balanced.status === 'builder') expect(output.builders.balanced.selectedLegs.every(x => ['Strong','Good'].includes(x.confidence) && x.estimatedProbability >= 62)).toBe(true) })
  it('returns valid no-builder outcomes without adding Moderate legs', () => { const { fixture, research } = copies(1); research.fixtures[0].dataQuality = 'partial'; const output = analyse(fixture, research, settings()); expect(output.builders.highProbability.status).toBe('no_qualifying_builder'); expect(output.builders.balanced.status).toBe('no_qualifying_builder') })
})
