import { describe, expect, it } from 'vitest'
import { analyse, defaultModelSettings, smoothRate, V13_SCORING } from './analysisModel'
import type { FixturePack, MarketEvidence, ResearchPack, TeamEvidence } from './types'

const source = { sourceId: 'current', url: 'https://example.com/current', title: 'Current league data', retrievedAt: '2026-09-02T09:00:00Z' }
const market = (side: 'home'|'away', hits = 2, sampleSize = 2): MarketEvidence => ({ marketKey: 'team_score_1_plus', marketGroup: 'team_to_score', selectionLabel: side === 'home' ? 'Home scores' : 'Home opponent concedes', teamSide: side, threshold: .5, sampleSize, hits, recentSampleSize: sampleSize, recentHits: hits, venueSampleSize: 1, venueHits: hits ? 1 : 0, underlyingSupportPercent: null, sourceIds: ['current'] })
const team = (evidence: MarketEvidence[]): TeamEvidence => ({ currentSeasonLeagueMatches: 2, currentSeasonForm: { summary: 'Current only', lastFive: null, lastTen: null, homeOrAway: '1/1', goalsScored: 2, goalsConceded: 0, sourceIds: ['current'] }, marketHitRates: evidence, optionalMetrics: {} })
const input = (opponentHits = 1, benchmark = true, candidate = true): [FixturePack, ResearchPack] => {
 const fixture: FixturePack = { packName:'FixturePack v1', schemaVersion:'1.0.0', fixtureDate:'2026-09-03', generatedAt:'2026-09-02T09:00:00Z', competitions:['Premier League'], fixtures:[{ fixtureId:'f', competition:'Premier League', homeTeam:'Home', awayTeam:'Away', kickOff:{utc:'2026-09-03T14:00:00Z',localDate:'2026-09-03',localTime:'15:00',timezone:'Europe/London'} }] }
 const context = { status:'unknown' as const, impact:'unknown' as const, scope:'both' as const, application:'descriptive_only' as const, detail:null, sourceIds:['current'] }
 const research: ResearchPack = { packName:'ResearchPack v1', schemaVersion:'1.3.0', fixturePackRef:{schemaVersion:'1.0.0',fixtureDate:'2026-09-03'},generatedAt:'2026-09-02T09:00:00Z',dataStatus:'real',sources:[source],competitionBenchmarks:benchmark?[{competition:'Premier League',currentSeasonCompletedFixtures:20,marketBenchmarks:[{marketKey:'team_score_1_plus',marketGroup:'team_to_score',selectionLabel:'League teams score',sampleSize:40,hits:24,supportPercent:60,sourceIds:['current']}],optionalMetrics:{}}]:[],fixtures:[{fixtureId:'f',competition:'Premier League',homeTeam:'Home',awayTeam:'Away',homeEvidence:team(candidate?[market('home')]:[]),awayEvidence:team([market('away',opponentHits)]),opponentStrength:context,teamNews:context,fixtureCongestion:context,managerialContext:context,reasonsFor:[],reasonsAgainst:[],dataQuality:'partial'}] }
 return [fixture,research]
}
const settings=()=>defaultModelSettings('2026-09-02T10:00:00Z',24)
describe('current-season benchmark model v1.3',()=>{
 it('uses the documented exact empirical-Bayes smoothing',()=>{ expect(V13_SCORING.priorFixtures).toBe(4); expect(smoothRate(2,2,60)).toBeCloseTo(73.3333333333,8) })
 it('shrinks 2/2 evidence and caps it below Strong',()=>{ const [f,r]=input(); const c=analyse(f,r,settings()).candidates.find(x=>x.supportingEvidence.evidenceUseTrace?.candidate?.startsWith('2/2'))!; expect(c.supportingEvidence.hitRatePercent).toBe(73); expect(c.confidence).not.toBe('Strong'); expect(c.dataQuality).toBe('usable_partial') })
 it('materially moderates scoring when the opponent has conceded 0/2',()=>{ const [f,a]=input(2),[,b]=input(0); expect(analyse(f,b,settings()).candidates[0].estimatedProbability).toBeLessThan(analyse(f,a,settings()).candidates[0].estimatedProbability) })
 it('ignores unrelated opponent-scoped context',()=>{ const [f,r]=input(); const base=analyse(f,r,settings()).candidates.find(x=>x.correlation.teamSide==='home')!.estimatedProbability; r.fixtures[0].teamNews={status:'known',impact:'material',scope:'away',application:'candidate_penalty',detail:'Away disruption',sourceIds:['current']}; expect(analyse(f,r,settings()).candidates.find(x=>x.correlation.teamSide==='home')!.estimatedProbability).toBe(base) })
 it.each([['candidate',false,true],['benchmark',true,false]])('marks missing %s evidence insufficient',(_name,candidate,benchmark)=>{const[f,r]=input(1,benchmark,candidate);const c=analyse(f,r,settings()).candidates.find(x=>x.marketKey==='team_score_1_plus'); if(c){expect(c.dataQuality).toBe('insufficient');expect(c.confidence).toBe('Avoid');expect(c.missingCoreEvidence?.length).toBeGreaterThan(0)}})
 it('is deterministic and excludes partial evidence from the high-probability builder',()=>{const[f,r]=input();const a=analyse(f,r,settings());expect(JSON.stringify(analyse(f,r,settings()))).toBe(JSON.stringify(a));expect(a.builders.highProbability.status).toBe('no_qualifying_builder')})
})
