import { describe, expect, it } from 'vitest'
import { MARKET_CONTRACT, MARKET_FAMILY_CONTRACT, preflightCandidate } from './marketContract'
import { MARKET_GROUPS, type MarketEvidence, type ResearchPack } from './types'

const evidence = (marketKey:string, marketGroup:MarketEvidence['marketGroup'], threshold:number|null, evidenceRole:MarketEvidence['evidenceRole'], teamSide:'home'|'away'|'match'='home'):MarketEvidence => ({ evidenceRole, marketKey, marketGroup, threshold, teamSide, selectionLabel: marketKey, sampleSize:8,hits:6,recentSampleSize:5,recentHits:4,venueSampleSize:4,venueHits:3,underlyingSupportPercent:null,sourceIds:['source'] })
const base = ():ResearchPack => { const form={summary:'current',lastFive:null,lastTen:null,homeOrAway:null,goalsScored:null,goalsConceded:null,sourceIds:['source']}; const context={status:'unknown' as const,impact:'unknown' as const,scope:'both' as const,application:'descriptive_only' as const,detail:null,sourceIds:['source']}; return {packName:'ResearchPack v1',schemaVersion:'1.4.0',fixturePackRef:{schemaVersion:'1.0.0',fixtureDate:'2026-09-03'},generatedAt:'2026-09-03T09:00:00Z',dataStatus:'real',sources:[{sourceId:'source',url:'https://example.com',title:'source',retrievedAt:'2026-09-03T08:00:00Z'}],competitionBenchmarks:[{competition:'Premier League',currentSeasonCompletedFixtures:20,marketBenchmarks:[],optionalMetrics:{}}],fixtures:[{fixtureId:'fixture',competition:'Premier League',homeTeam:'Home',awayTeam:'Away',homeEvidence:{currentSeasonForm:form,currentSeasonLeagueMatches:8,marketHitRates:[],optionalMetrics:{}},awayEvidence:{currentSeasonForm:form,currentSeasonLeagueMatches:8,marketHitRates:[],optionalMetrics:{}},opponentStrength:context,teamNews:context,fixtureCongestion:context,managerialContext:context,reasonsFor:[],reasonsAgainst:[],dataQuality:'partial'}]} }
const render = (template:string, side:MarketEvidence['teamSide']) => template.replace('{team}', side === 'home' ? 'Home' : side === 'away' ? 'Away' : '')
function complete(index:number): { pack: ResearchPack; fixture: ResearchPack['fixtures'][number]; array: 'homeEvidence' | 'awayEvidence'; candidate: MarketEvidence; contract: (typeof MARKET_CONTRACT)[number] } { const pack=base(), contract=MARKET_CONTRACT[index], fixture=pack.fixtures[0], candidate=evidence(contract.marketKey,contract.marketGroup,contract.threshold,'candidate_market',(contract.candidateTeamSide[0] === 'away' ? 'away' : contract.candidateTeamSide[0] === 'match' ? 'match' : 'home')); candidate.selectionLabel=render(contract.selectionLabel.template,candidate.teamSide); const array=contract.candidateTeamSide[0] === 'away' ? 'awayEvidence' : 'homeEvidence'; fixture[array].marketHitRates.push(candidate); for(const rule of contract.support){ const target=rule.location==='candidate'?fixture[array]:array==='homeEvidence'?fixture.awayEvidence:fixture.homeEvidence; const support=evidence(rule.marketKey,rule.marketGroup,rule.threshold,'supporting_only',target===fixture.homeEvidence?'home':'away'); support.selectionLabel=render(rule.selectionLabel.template,support.teamSide); target.marketHitRates.push(support) } pack.competitionBenchmarks![0].marketBenchmarks.push({marketKey:contract.marketKey,marketGroup:contract.marketGroup,threshold:contract.threshold,selectionLabel:contract.label,sampleSize:20,hits:12,supportPercent:60,sourceIds:['source']}); return {pack,fixture,array,candidate,contract} }

describe('canonical market contract',()=>{
 it('contains every dropdown family exactly once in the family view',()=>expect(MARKET_FAMILY_CONTRACT.map(x=>x.marketGroup)).toEqual(MARKET_GROUPS))
 it('gives every candidate and supporting-only variant a deterministic label rule',()=>{ for(const item of MARKET_CONTRACT){expect(item.selectionLabel.template).toBeTruthy();expect(item.candidateTeamSide.length).toBeGreaterThan(0);expect(item.support.length).toBeGreaterThan(0);for(const support of item.support) expect(support.selectionLabel.template).toBeTruthy();expect(item.benchmark).toEqual({marketKey:item.marketKey,marketGroup:item.marketGroup,threshold:item.threshold});expect(typeof item.venueRequired).toBe('boolean');expect(item.prohibitedSubstitutions.length).toBeGreaterThan(0) } })
 it.each(MARKET_CONTRACT.map((_,i)=>i))('accepts complete exact variant %i',(i)=>{const {pack,fixture,array}=complete(i);expect(preflightCandidate(pack,fixture,array,0).issues).toEqual([])})
 it('reports exact wrong support key, role, threshold, side/group, venue and benchmark gates',()=>{const {pack,fixture,array,contract}=complete(0);const support=fixture.awayEvidence.marketHitRates[0]; support.marketKey='wrong'; const audit=preflightCandidate(pack,fixture,array,0); expect(audit.issues[0].message).toContain(contract.support[0].marketKey); support.marketKey=contract.support[0].marketKey; support.evidenceRole='candidate_market'; expect(preflightCandidate(pack,fixture,array,0).issues.some(x=>x.code==='missing_required_support')).toBe(true); support.evidenceRole='supporting_only'; support.threshold=2.5; expect(preflightCandidate(pack,fixture,array,0).issues.some(x=>x.code==='missing_required_support')).toBe(true); support.threshold=null; support.marketGroup='total_goals'; expect(preflightCandidate(pack,fixture,array,0).issues.some(x=>x.code==='missing_required_support')).toBe(true); support.marketGroup=contract.marketGroup; fixture.homeEvidence.marketHitRates[0].venueSampleSize=null; expect(preflightCandidate(pack,fixture,array,0).issues.some(x=>x.code==='missing_venue_requirement')).toBe(true); fixture.homeEvidence.marketHitRates[0].venueSampleSize=4; pack.competitionBenchmarks![0].marketBenchmarks=[]; expect(preflightCandidate(pack,fixture,array,0).issues.some(x=>x.code==='missing_matching_benchmark')).toBe(true) })
 it('requires reciprocal support for both home and away candidates',()=>{for(const key of ['team_to_score_1_plus','team_goals_over_1_5','team_shots_8_plus']){const index=MARKET_CONTRACT.findIndex(x=>x.marketKey===key);for(const side of ['home','away'] as const){const setup=complete(index);if(side==='away'&&setup.array==='homeEvidence'){const c=setup.fixture.homeEvidence.marketHitRates.shift()!;c.teamSide='away';c.selectionLabel=render(setup.contract.selectionLabel.template,c.teamSide);setup.fixture.awayEvidence.marketHitRates.unshift(c);const required=setup.fixture.awayEvidence.marketHitRates.splice(1);for(const support of required){support.teamSide='home';const rule=setup.contract.support.find(x=>x.marketKey===support.marketKey)!;support.selectionLabel=render(rule.selectionLabel.template,support.teamSide)}setup.fixture.homeEvidence.marketHitRates.push(...required);setup.array='awayEvidence'}expect(preflightCandidate(setup.pack,setup.fixture,setup.array,0).issues).toEqual([]);const opposite=setup.array==='homeEvidence'?setup.fixture.awayEvidence:setup.fixture.homeEvidence;opposite.marketHitRates=[];expect(preflightCandidate(setup.pack,setup.fixture,setup.array,0).issues[0].code).toBe('missing_required_support')}}})
 it('does not accept cross-family or incompatible threshold substitutions',()=>{const {pack,fixture,array}=complete(MARKET_CONTRACT.findIndex(x=>x.marketKey==='team_to_score_1_plus'));fixture[array].marketHitRates[0].marketGroup='team_goals';expect(preflightCandidate(pack,fixture,array,0).issues[0].code).toBe('unsupported_candidate_contract');fixture[array].marketHitRates[0].marketGroup='team_to_score';fixture[array].marketHitRates[0].threshold=1.5;expect(preflightCandidate(pack,fixture,array,0).issues[0].code).toBe('unsupported_candidate_contract')})
 it.each([['match_result_home_win','Home win'],['match_result_away_win','Away win'],['match_result_draw','Draw']])('%s accepts only its static exact label',(key,label)=>{const setup=complete(MARKET_CONTRACT.findIndex(x=>x.marketKey===key));expect(setup.candidate.selectionLabel).toBe(label);for(const bad of [`Arsenal ${label}`,`${label} today`,key]){setup.candidate.selectionLabel=bad;const audit=preflightCandidate(setup.pack,setup.fixture,setup.array,0);expect(audit.labelFailures[0]).toMatchObject({path:`${audit.path}.selectionLabel`,marketKey:key,receivedLabel:bad,expectedLabel:label,evidenceRole:'candidate_market'});expect(audit.issues[0].message).toBe(`Candidate ${key} requires selectionLabel \`${label}\`; received \`${bad}\`.`)}})
 it('requires exact team names in dynamic candidate labels',()=>{const setup=complete(MARKET_CONTRACT.findIndex(x=>x.marketKey==='team_goals_over_1_5'));expect(setup.candidate.selectionLabel).toBe('Home over 1.5 goals');setup.candidate.selectionLabel='Away over 1.5 goals';expect(preflightCandidate(setup.pack,setup.fixture,setup.array,0).labelFailures[0].expectedLabel).toBe('Home over 1.5 goals')})
 it('rejects a label carrying another threshold',()=>{const setup=complete(MARKET_CONTRACT.findIndex(x=>x.marketKey==='total_goals_over_1_5'));setup.candidate.selectionLabel='Over 2.5 total goals';expect(preflightCandidate(setup.pack,setup.fixture,setup.array,0).labelFailures[0]).toMatchObject({receivedLabel:'Over 2.5 total goals',expectedLabel:'Over 1.5 total goals'})})
 it('audits supporting-only labels against their own rule',()=>{const setup=complete(0);const support=setup.fixture.awayEvidence.marketHitRates[0];support.selectionLabel='Home loses';const audit=preflightCandidate(setup.pack,setup.fixture,setup.array,0);expect(audit.labelFailures[0]).toMatchObject({marketKey:'opponent_loses',receivedLabel:'Home loses',expectedLabel:'Away loses',evidenceRole:'supporting_only'});expect(audit.labelFailures[0].path).toContain('awayEvidence.marketHitRates[0].selectionLabel')})
})
