import { describe, expect, it } from 'vitest'
import { analyse, defaultModelSettings } from './analysisModel'
import { marketCoverageLabel } from './analysisPresentation'
import type { FixturePack, MarketEvidence, ResearchPack, TeamEvidence } from './types'
const source={sourceId:'s',url:'https://example.com',title:'Current evidence',retrievedAt:'2026-09-02T09:00:00Z'}
const evidence=(role:MarketEvidence['evidenceRole'], key:string, group:MarketEvidence['marketGroup'], side:'home'|'away', hits=6):MarketEvidence=>({evidenceRole:role,marketKey:key,marketGroup:group,selectionLabel:key,teamSide:side,threshold:.5,sampleSize:6,hits,recentSampleSize:6,recentHits:hits,venueSampleSize:3,venueHits:3,underlyingSupportPercent:null,sourceIds:['s']})
const team=(rates:MarketEvidence[]):TeamEvidence=>({currentSeasonLeagueMatches:6,currentSeasonForm:{summary:'current',lastFive:null,lastTen:null,homeOrAway:'3',goalsScored:null,goalsConceded:null,sourceIds:['s']},marketHitRates:rates,optionalMetrics:{}})
const packs=():[FixturePack,ResearchPack]=>{const fixture:FixturePack={packName:'FixturePack v1',schemaVersion:'1.0.0',fixtureDate:'2026-09-03',generatedAt:'2026-09-02T09:00:00Z',competitions:['Premier League'],fixtures:[{fixtureId:'f',competition:'Premier League',homeTeam:'H',awayTeam:'A',kickOff:{utc:'2026-09-03T14:00:00Z',localDate:'2026-09-03',localTime:'15:00',timezone:'Europe/London'}}]};const c={status:'unknown' as const,impact:'unknown' as const,scope:'both' as const,application:'descriptive_only' as const,detail:null,sourceIds:['s']};const research:ResearchPack={packName:'ResearchPack v1',schemaVersion:'1.4.0',fixturePackRef:{schemaVersion:'1.0.0',fixtureDate:'2026-09-03'},generatedAt:'2026-09-02T09:00:00Z',dataStatus:'real',sources:[source],competitionBenchmarks:[{competition:'Premier League',currentSeasonCompletedFixtures:20,marketBenchmarks:[{marketKey:'team_to_score_1_plus',marketGroup:'team_to_score',selectionLabel:'league scoring',threshold:.5,sampleSize:40,hits:24,supportPercent:60,sourceIds:['s']}],optionalMetrics:{}}],fixtures:[{fixtureId:'f',competition:'Premier League',homeTeam:'H',awayTeam:'A',homeEvidence:team([evidence('candidate_market','team_to_score_1_plus','team_to_score','home')]),awayEvidence:team([evidence('supporting_only','team_to_concede_1_plus','team_to_score','away',4)]),opponentStrength:c,teamNews:c,fixtureCongestion:c,managerialContext:c,reasonsFor:[],reasonsAgainst:[],dataQuality:'partial'}]};return[fixture,research]}
describe('ResearchPack v1.4 market coverage',()=>{
 it('uses conceded support without emitting it and provides complete traces and partial reasons',()=>{const[f,r]=packs();const out=analyse(f,r,defaultModelSettings('2026-09-02T10:00:00Z',24));expect(out.candidates).toHaveLength(1);expect(out.candidates[0].marketKey).toBe('team_to_score_1_plus');expect(out.candidates[0].supportingEvidence.evidenceUseTrace?.opponent).toContain('team_to_concede');expect(Object.entries(out.candidates[0].supportingEvidence.evidenceUseTrace!).filter(([k])=>k!=='sourceIds').every(([,v])=>typeof v==='string'&&v.length>0)).toBe(true);expect(out.candidates[0].reasonsAgainst.join(' ')).toMatch(/small-sample/i)})
 it('does not create result or specialist candidates from generic goals fields and is deterministic',()=>{const[f,r]=packs();r.fixtures[0].homeEvidence.currentSeasonForm.goalsScored=12;const a=analyse(f,r,defaultModelSettings('2026-09-02T10:00:00Z',24));expect(a.candidates.every(c=>!['match_result','double_chance','draw_no_bet','total_goals','total_corners','team_cards','team_shots','team_shots_on_target'].includes(c.marketGroup))).toBe(true);expect(JSON.stringify(analyse(f,r,defaultModelSettings('2026-09-02T10:00:00Z',24)))).toBe(JSON.stringify(a))})
 it('does not create specialist evidence or candidates when manual availability is changed to available',()=>{const[f,r]=packs();const unknown=analyse(f,r,defaultModelSettings('2026-09-02T10:00:00Z',24));const settings=defaultModelSettings('2026-09-02T10:00:00Z',24);for(const group of ['total_corners','team_corners','total_cards','team_cards','team_shots','team_shots_on_target'] as const)settings.marketAvailability[group]='available';const available=analyse(f,r,settings);expect(available.candidates).toEqual(unknown.candidates);expect(available.candidates.some(candidate=>['total_corners','team_corners','total_cards','team_cards','team_shots','team_shots_on_target'].includes(candidate.marketGroup))).toBe(false)})
 it('audits a team-to-score-only pack with deterministic source-specific reasons',()=>{const[f,r]=packs();const first=analyse(f,r,defaultModelSettings('2026-09-02T10:00:00Z',24));const second=analyse(f,r,defaultModelSettings('2026-09-02T10:00:00Z',24));expect(second.marketCoverage).toEqual(first.marketCoverage);expect(first.marketCoverage.find(x=>x.marketGroup==='team_to_score')).toMatchObject({candidateMarketRecordsSupplied:1,supportingOnlyRecordsSupplied:1,matchingBenchmarksSupplied:1,candidateCount:1,unavailableReason:null});expect(first.marketCoverage.find(x=>x.marketGroup==='total_corners')?.unavailableReason).toContain('specified source route was attempted');for(const group of ['total_cards','team_cards','team_shots','team_shots_on_target'] as const)expect(first.marketCoverage.find(x=>x.marketGroup===group)?.unavailableReason).toContain('current-season')})
 it('does not turn an average-only optional metric into threshold evidence',()=>{const[f,r]=packs();r.fixtures[0].homeEvidence.optionalMetrics.corners={value:5.4,sourceIds:['s']};r.competitionBenchmarks![0].optionalMetrics.corners={value:10.2,sourceIds:['s']};const out=analyse(f,r,defaultModelSettings('2026-09-02T10:00:00Z',24));expect(out.candidates.some(candidate=>['total_corners','team_corners'].includes(candidate.marketGroup))).toBe(false);expect(out.marketCoverage.find(item=>item.marketGroup==='team_corners')?.unavailableReason).toContain('specified source route was attempted')})
 it.each(['total_corners','team_corners','total_cards','team_cards','team_shots','team_shots_on_target'] as const)('creates %s coverage only with dedicated support and an exact benchmark',(group)=>{const[f,r]=packs();const key=`${group}_threshold`;r.fixtures[0].homeEvidence.marketHitRates=[evidence('candidate_market',key,group,'home')];r.fixtures[0].awayEvidence.marketHitRates=[evidence('supporting_only',key,group,'away')];r.competitionBenchmarks![0].marketBenchmarks=[{marketKey:key,marketGroup:group,selectionLabel:key,threshold:.5,sampleSize:20,hits:12,supportPercent:60,sourceIds:['s']}];const complete=analyse(f,r,defaultModelSettings('2026-09-02T10:00:00Z',24));expect(complete.marketCoverage.find(x=>x.marketGroup===group)).toMatchObject({status:'analysed',candidateCount:1});r.fixtures[0].awayEvidence.marketHitRates=[];const missingSupport=analyse(f,r,defaultModelSettings('2026-09-02T10:00:00Z',24));expect(missingSupport.marketCoverage.find(x=>x.marketGroup===group)).toMatchObject({status:'unavailable',candidateCount:0});expect(missingSupport.candidates).toHaveLength(0)})
 it.each(['both_teams_to_score','total_goals','clean_sheet','match_result'] as const)('gates dedicated %s evidence',(group)=>{const[f,r]=packs();const key=group;r.fixtures[0].homeEvidence.marketHitRates=[evidence('candidate_market',key,group,'home')];const support=group==='both_teams_to_score'?[evidence('supporting_only','home_score',group,'home'),evidence('supporting_only','home_concede',group,'home')]:[];r.fixtures[0].homeEvidence.marketHitRates.push(...support);r.fixtures[0].awayEvidence.marketHitRates=group==='both_teams_to_score'?[evidence('supporting_only','away_score',group,'away'),evidence('supporting_only','away_concede',group,'away')]:group==='total_goals'?[]:[evidence('supporting_only',group==='clean_sheet'?'failed_to_score':key,group,'away')];r.competitionBenchmarks![0].marketBenchmarks=[{marketKey:key,marketGroup:group,selectionLabel:key,threshold:.5,sampleSize:20,hits:12,supportPercent:60,sourceIds:['s']}];expect(analyse(f,r,defaultModelSettings('2026-09-02T10:00:00Z',24)).marketCoverage.find(x=>x.marketGroup===group)?.status).toBe('analysed');r.competitionBenchmarks![0].marketBenchmarks=[];expect(analyse(f,r,defaultModelSettings('2026-09-02T10:00:00Z',24)).marketCoverage.find(x=>x.marketGroup===group)?.unavailableReason).toContain('Matching competition benchmark not supplied')})
 it('renders model diagnostics without deriving availability or scores',()=>{const[f,r]=packs();const coverage=analyse(f,r,defaultModelSettings('2026-09-02T10:00:00Z',24)).marketCoverage.find(x=>x.marketGroup==='team_shots')!;const before=structuredClone(coverage);expect(marketCoverageLabel(coverage)).toBe(coverage.unavailableReason);expect(coverage).toEqual(before)})
})
