import { describe, expect, it } from 'vitest'
import { MARKET_CONTRACT, MARKET_FAMILY_CONTRACT, preflightCandidate } from './marketContract'
import { MARKET_GROUPS, type MarketEvidence, type ResearchPack } from './types'

const evidence = (marketKey:string, marketGroup:MarketEvidence['marketGroup'], threshold:number|null, evidenceRole:MarketEvidence['evidenceRole'], teamSide:'home'|'away'|'match'='home'):MarketEvidence => ({ evidenceRole, marketKey, marketGroup, threshold, teamSide, selectionLabel: marketKey, sampleSize:8,hits:6,recentSampleSize:5,recentHits:4,venueSampleSize:4,venueHits:3,underlyingSupportPercent:null,sourceIds:['source'] })
const base = ():ResearchPack => { const form={summary:'current',lastFive:null,lastTen:null,homeOrAway:null,goalsScored:null,goalsConceded:null,sourceIds:['source']}; const context={status:'unknown' as const,impact:'unknown' as const,scope:'both' as const,application:'descriptive_only' as const,detail:null,sourceIds:['source']}; return {packName:'ResearchPack v1',schemaVersion:'1.4.0',fixturePackRef:{schemaVersion:'1.0.0',fixtureDate:'2026-09-03'},generatedAt:'2026-09-03T09:00:00Z',dataStatus:'real',sources:[{sourceId:'source',url:'https://example.com',title:'source',retrievedAt:'2026-09-03T08:00:00Z'}],competitionBenchmarks:[{competition:'Premier League',currentSeasonCompletedFixtures:20,marketBenchmarks:[],optionalMetrics:{}}],fixtures:[{fixtureId:'fixture',competition:'Premier League',homeTeam:'Home',awayTeam:'Away',homeEvidence:{currentSeasonForm:form,currentSeasonLeagueMatches:8,marketHitRates:[],optionalMetrics:{}},awayEvidence:{currentSeasonForm:form,currentSeasonLeagueMatches:8,marketHitRates:[],optionalMetrics:{}},opponentStrength:context,teamNews:context,fixtureCongestion:context,managerialContext:context,reasonsFor:[],reasonsAgainst:[],dataQuality:'partial'}]} }
function complete(index:number): { pack: ResearchPack; fixture: ResearchPack['fixtures'][number]; array: 'homeEvidence' | 'awayEvidence'; candidate: MarketEvidence; contract: (typeof MARKET_CONTRACT)[number] } { const pack=base(), contract=MARKET_CONTRACT[index], fixture=pack.fixtures[0], candidate=evidence(contract.marketKey,contract.marketGroup,contract.threshold,'candidate_market',(contract.candidateTeamSide[0] === 'away' ? 'away' : contract.candidateTeamSide[0] === 'match' ? 'match' : 'home')); candidate.selectionLabel=contract.selectionLabelPattern === '.+' ? contract.marketKey : contract.selectionLabelPattern.replaceAll('^','').replaceAll('$',''); const array=contract.candidateTeamSide[0] === 'away' ? 'awayEvidence' : 'homeEvidence'; fixture[array].marketHitRates.push(candidate); for(const rule of contract.support){ const target=rule.location==='candidate'?fixture[array]:array==='homeEvidence'?fixture.awayEvidence:fixture.homeEvidence; target.marketHitRates.push(evidence(rule.marketKey,rule.marketGroup,rule.threshold,'supporting_only',target===fixture.homeEvidence?'home':'away')) } pack.competitionBenchmarks![0].marketBenchmarks.push({marketKey:contract.marketKey,marketGroup:contract.marketGroup,threshold:contract.threshold,selectionLabel:contract.label,sampleSize:20,hits:12,supportPercent:60,sourceIds:['source']}); return {pack,fixture,array,candidate,contract} }

describe('canonical market contract',()=>{
 it('contains every dropdown family exactly once in the family view',()=>expect(MARKET_FAMILY_CONTRACT.map(x=>x.marketGroup)).toEqual(MARKET_GROUPS))
 it('gives every variant explicit sides, support, source, venue and exact benchmark rules',()=>{ for(const item of MARKET_CONTRACT){expect(item.candidateTeamSide.length).toBeGreaterThan(0);expect(item.support.length).toBeGreaterThan(0);expect(item.benchmark).toEqual({marketKey:item.marketKey,marketGroup:item.marketGroup,threshold:item.threshold});expect(typeof item.venueRequired).toBe('boolean');expect(item.prohibitedSubstitutions.length).toBeGreaterThan(0) } })
 it.each(MARKET_CONTRACT.map((_,i)=>i))('accepts complete exact variant %i',(i)=>{const {pack,fixture,array}=complete(i);expect(preflightCandidate(pack,fixture,array,0).issues).toEqual([])})
 it('reports exact wrong support key, role, threshold, side/group, venue and benchmark gates',()=>{const {pack,fixture,array,contract}=complete(0);const support=fixture.awayEvidence.marketHitRates[0]; support.marketKey='wrong'; const audit=preflightCandidate(pack,fixture,array,0); expect(audit.issues[0].message).toContain(contract.support[0].marketKey); support.marketKey=contract.support[0].marketKey; support.evidenceRole='candidate_market'; expect(preflightCandidate(pack,fixture,array,0).issues.some(x=>x.code==='missing_required_support')).toBe(true); support.evidenceRole='supporting_only'; support.threshold=2.5; expect(preflightCandidate(pack,fixture,array,0).issues.some(x=>x.code==='missing_required_support')).toBe(true); support.threshold=null; support.marketGroup='total_goals'; expect(preflightCandidate(pack,fixture,array,0).issues.some(x=>x.code==='missing_required_support')).toBe(true); support.marketGroup=contract.marketGroup; fixture.homeEvidence.marketHitRates[0].venueSampleSize=null; expect(preflightCandidate(pack,fixture,array,0).issues.some(x=>x.code==='missing_venue_requirement')).toBe(true); fixture.homeEvidence.marketHitRates[0].venueSampleSize=4; pack.competitionBenchmarks![0].marketBenchmarks=[]; expect(preflightCandidate(pack,fixture,array,0).issues.some(x=>x.code==='missing_matching_benchmark')).toBe(true) })
 it('requires reciprocal support for both home and away candidates',()=>{for(const key of ['team_to_score_1_plus','team_goals_over_1_5','team_shots_8_plus']){const index=MARKET_CONTRACT.findIndex(x=>x.marketKey===key);for(const side of ['home','away'] as const){const setup=complete(index);if(side==='away'&&setup.array==='homeEvidence'){const c=setup.fixture.homeEvidence.marketHitRates.shift()!;c.teamSide='away';setup.fixture.awayEvidence.marketHitRates.unshift(c);const required=setup.fixture.awayEvidence.marketHitRates.splice(1);setup.fixture.homeEvidence.marketHitRates.push(...required);setup.array='awayEvidence'}expect(preflightCandidate(setup.pack,setup.fixture,setup.array,0).issues).toEqual([]);const opposite=setup.array==='homeEvidence'?setup.fixture.awayEvidence:setup.fixture.homeEvidence;opposite.marketHitRates=[];expect(preflightCandidate(setup.pack,setup.fixture,setup.array,0).issues[0].code).toBe('missing_required_support')}}})
 it('does not accept cross-family or incompatible threshold substitutions',()=>{const {pack,fixture,array}=complete(MARKET_CONTRACT.findIndex(x=>x.marketKey==='team_to_score_1_plus'));fixture[array].marketHitRates[0].marketGroup='team_goals';expect(preflightCandidate(pack,fixture,array,0).issues[0].code).toBe('unsupported_candidate_contract');fixture[array].marketHitRates[0].marketGroup='team_to_score';fixture[array].marketHitRates[0].threshold=1.5;expect(preflightCandidate(pack,fixture,array,0).issues[0].code).toBe('unsupported_candidate_contract')})
})
