export const RESEARCH_ACQUISITION_POLICY = `RESEARCH SOURCE HIERARCHY for Premier League and Championship (apply per individual evidence component; a fallback is allowed only when the earlier provider does not expose that exact value):
1. Official Premier League / EFL fixture pages — fixture discovery and kick-off verification only. They are statistical evidence only when an official completed-match centre exposes the exact numeric team-level metric.
2. FootyStats current-season league/team/statistics pages — preferred aggregate source for results, home/away W/D/L, double chance, draw no bet, BTTS, total goals, team goals, team to score, clean sheets, total corners, team corners, cards, shots and shots on target, but only when statistics pages expose exact current-season values or an exact manually countable completed-match table. Never use FootyStats prediction, betting-system, odds, tip or bookmaker material.
3. SoccerStats current-season league/team/home/away/statistics pages — fallback aggregate source only when FootyStats does not expose the exact required component, especially for results, goals, BTTS, clean sheets, match corners, team corners-for, opponent corners-against and home/away splits. An average alone is never sufficient: require explicit hit counts/percentages or exact counts manually derived from a completed-match table.
4. StatBunker current-season competition and club pages — targeted fallback only for team discipline and team-card evidence. Use team-level current-season competition statistics and exact completed-match records or counts; never aggregate or sum player statistics into team evidence.
5. Direct completed-match pages, in this exact order: FotMob; then SofaScore; then official Premier League or EFL completed-match centre. Use these only when aggregate sources cannot provide an exact threshold count for explicit per-match team corners, total/team cards, total/team shots or total/team shots on target. The page must visibly expose the numeric team-level stat; merely advertising “match stats” is not evidence.
6. WhoScored — Premier League-only fallback for team shots and shots on target when it exposes current-season team-level values or direct completed-match values. Never substitute player data or ratings.
7. PROHIBITED: WinDrawWin is prohibited. Also prohibit Flashscore; bookmaker, tipster, odds or prediction pages; player-stat aggregation; generic averages; referee trends; xG-only substitutes; possession; narrative reports; and inferred figures.

NO DOUBLE HANDLING: Assign source ownership at the individual evidence-component level. A candidate record, opponent-support record, venue record and competition benchmark may use different sources only because they are distinct components, never duplicate measurements of the same underlying sample. Never combine, average, merge or double-count the same team/metric/sample from multiple providers. Once a source supplies a valid component, retain that source's value and do not collect a fallback duplicate. If providers expose conflicting values for the exact same current-season metric and scope, do not choose silently or average them: treat only that market component as unreliable, omit its affected candidate, and report that market unavailable. Other independently supported markets remain eligible.

REQUIRED PRIVATE WORKFLOW FOR EVERY DISCOVERED FIXTURE (perform before producing JSON):
A. Create a private research checklist.
B. Identify every completed current-season league match for the home team, the away team and the relevant competition benchmark dataset.
C. Attempt each market family independently; do not stop after team-to-score evidence is found.
D. For each supported threshold, collect only explicit current-season league observations and derive exact hit counts from verified completed matches where necessary.
E. Before emitting one candidate_market record, verify: exact candidate current-season threshold evidence; mandatory supporting_only opponent evidence; required current home/away venue evidence where the existing market matrix requires it; an exact same-marketKey, same-threshold competition benchmark; and declared source citations for every populated component.
F. If any mandatory component is missing, conflicting, not team-level, not current-season league-only, or merely an average/proxy, omit that candidate market. Never substitute a neutral value.

MANDATORY MARKET-FAMILY CHECKLIST — explicitly attempt all 14 families for every fixture:
1. Match result — attempt home win, away win and draw where exact W/D/L records, relevant venue evidence, opponent support and matching benchmark exist.
2. Double chance — attempt exact current W/D/L-derived double-chance records only where the existing schema and matrix can represent them without inference.
3. Draw no bet — attempt exact current result records, venue evidence, opponent support and benchmark only.
4. Both teams to score (BTTS) — attempt a dedicated BTTS candidate record, both teams' explicit scoring and conceding support, and matching BTTS benchmark. Team-to-score candidate evidence is not a dedicated BTTS record unless the existing model explicitly supports that relationship.
5. Total goals — attempt at least over 1.5 and over 2.5 using dedicated current match-total threshold counts and matching benchmarks.
6. Team goals — attempt team 1+ and team 2+ goals where supported, with candidate scoring threshold, opponent conceding threshold and matching benchmark.
7. Team to score — attempt team 1+ and team 2+ goals where supported, with candidate scoring threshold, opponent conceding threshold and matching benchmark.
8. Clean sheets — attempt candidate clean-sheet record, opponent failure-to-score support and matching benchmark.
9. Total corners — attempt match over 8.5 and over 9.5 corners using dedicated threshold evidence, relevant opponent corners-for/conceded support and exact benchmarks.
10. Team corners — attempt team over 3.5 and over 4.5 corners using dedicated threshold evidence, opponent corners-for/conceded support and exact benchmarks.
11. Total cards — attempt match over 2.5 and over 3.5 cards using explicit direct-match or valid team-level current-season observations; never derive cards from fouls, referee history, narrative or player-card totals.
12. Team cards — attempt team over 0.5 and over 1.5 cards using explicit direct-match or valid team-level current-season observations and required support/benchmarks; never derive cards from fouls, referee history, narrative or player-card totals.
13. Team shots — attempt 8+ and 10+ shots where exact values exist; require candidate threshold evidence, opponent shots-allowed support and benchmark.
14. Team shots on target — attempt 3+ and 4+ shots on target where exact values exist; require candidate threshold evidence, opponent shots-on-target-allowed support and benchmark.

“Unavailable” means the specified source route was attempted and exact required evidence could not be established; it must never mean “not researched.” Include every discovered fixture even where all families are insufficient. In model-owned coverage text, identify the first missing mandatory component, for example: “Team cards unavailable: no exact current-season team-card threshold observations found after StatBunker, FotMob, SofaScore and official match-centre checks.”; “BTTS unavailable: dedicated BTTS candidate evidence missing; team-to-score evidence is not a substitute.”; “Team corners unavailable: opponent corners-conceded support missing.”; “Match result unavailable: relevant venue W/D/L evidence missing.”; “Team shots unavailable: explicit opponent shots-allowed threshold support missing.” Do not manufacture a candidate because a route was checked.`
