import { MARKET_CONTRACT, MARKET_FAMILY_CONTRACT } from './marketContract';

export const CANONICAL_MARKET_MATRIX = MARKET_FAMILY_CONTRACT;

const marketMatrix = MARKET_FAMILY_CONTRACT.map(({ marketGroup, label }, index) => {
  const variants = MARKET_CONTRACT.filter(item => item.marketGroup === marketGroup)
  return `${index + 1}. ${label} [${marketGroup}] — ${variants.map(item => `${item.marketKey}: threshold ${item.threshold ?? 'null'}; selectionLabel \`${item.selectionLabel.template}\`; supporting_only ${item.support.map(rule => `${rule.location} ${rule.marketKey} (${rule.marketGroup}, threshold ${rule.threshold ?? 'null'}, selectionLabel \`${rule.selectionLabel.template}\`)`).join(' + ')}; candidate sides ${item.candidateTeamSide.join('/')}; ${item.venueRequired ? 'required venue evidence' : 'venue evidence not required'}; exact same-marketKey/same-threshold competition benchmark ${item.benchmark.marketKey}; source route ${item.sourceRoute}; prohibited ${item.prohibitedSubstitutions.join(', ')}`).join(' | ')}`
}).join("\n");

export const RESEARCH_ACQUISITION_POLICY = `SOURCE HIERARCHY (apply per evidence component; fall back only when the earlier provider does not expose that exact value):
1. Official Premier League / EFL fixture pages — fixture and kick-off verification only, except an official completed-match centre may evidence an exact numeric team-level statistic.
2. FootyStats current-season league/team/statistics pages — preferred aggregate source; use only exact current-season values or exact counts manually derived from a completed-match table, never its prediction, betting-system, tip, odds, or bookmaker material.
3. SoccerStats current-season league/team/home/away/statistics pages — exact-component aggregate fallback when FootyStats lacks that value. An average alone is never sufficient; require explicit hit counts/percentages or an exactly countable completed-match table.
4. FotMob — current-season team shots/shots-on-target where exact observations exist; direct completed-match pages for cards, shots, shots on target and missing corners.
5. SofaScore direct completed-match pages — fallback for visibly exposed numeric team-level cards, shots, shots on target and corners.
6. Official Premier League/EFL completed-match centre — final direct-match fallback for those exact numeric statistics.
7. StatBunker — current-season team-level discipline fallback only; never aggregate player statistics.
8. WhoScored — Premier League-only fallback for team shots and shots on target, using exact current-season team-level or completed-match values only.
9. PROHIBITED: WinDrawWin, Flashscore, bookmaker, tipster, prediction, odds, player aggregation, proxy, average-only, inferred evidence, referee trends, xG substitutes, possession, and narrative reports.

NO DOUBLE HANDLING: Assign one source owner to each individual evidence component. Candidate, supporting-only, venue, and benchmark components may have different owners because they are distinct. Once a valid source supplies a component, do not collect a fallback duplicate; never combine, average, merge, or double-count the same team/metric/sample. If providers conflict on the exact current-season metric and scope, do not choose or average: isolate the conflict, omit only the affected candidate, and report source conflict; independent markets remain eligible.

PRIVATE RESEARCH WORKFLOW (complete before JSON):
A. Create a private checklist for every fixture and its completed current-season league matches.
B. Attempt every matrix family independently; finding one family never satisfies or ends another family’s research.
C. Collect explicit current-season league threshold observations, manually counting only verified completed-match tables where necessary.
D. For every proposed candidate verify exact candidate evidence, mandatory supporting_only opponent evidence, required venue evidence where the matrix says required, an exact same-marketKey/same-threshold competition benchmark, and declared citations.
E. Omit the candidate-market record when any mandatory component is missing, conflicting, not team-level, not current-season league-only, or average/proxy/inferred. Never substitute between market groups or thresholds and never insert a neutral value.

CANONICAL MARKET MATRIX (exactly 14 families; attempt every row independently and omit a candidate_market record if any mandatory component cannot be sourced):
selectionLabel is contract data, not prose. For every record, emit the exact label shown in this matrix, replacing only the {team} placeholder with the record's exact homeTeam or awayTeam. Do not replace a static label with a team name or paraphrase it.
${marketMatrix}

MANDATORY V1.5 PRE-OUTPUT AUDIT CONTRACT: The exact location is ResearchPack.marketResearchAudit (JSON path $.researchPack.marketResearchAudit inside AnalysisPack, or $.marketResearchAudit for a standalone ResearchPack). It is an array, never an object. Except for the no-fixture case below, it contains one and only one entry for each of the 14 marketGroup enum values in the canonical matrix. Every entry is exactly this object; every shown field is required and additional properties are forbidden:
{ "marketGroup": "match_result", "attempted": true, "routesAttempted": ["official_fixture"], "candidateEvidenceFound": true, "supportEvidenceFound": true, "benchmarkFound": true, "status": "available", "firstBlockingReason": null, "sourceIds": ["declared-source-id"] }
marketGroup permits exactly "match_result", "double_chance", "draw_no_bet", "both_teams_to_score", "total_goals", "team_goals", "team_to_score", "clean_sheet", "total_corners", "team_corners", "total_cards", "team_cards", "team_shots", or "team_shots_on_target". routesAttempted is a non-empty, unique, correctly ordered array using only "official_fixture", "footystats", "soccerstats", "fotmob", "sofascore", "official_match_centre", "statbunker", or "whoscored". status permits exactly "available" or "unavailable". sourceIds is a non-empty array of unique, non-empty IDs declared in ResearchPack.sources. firstBlockingReason is exactly one of null, "missing_candidate_observation", "missing_support_observation", "missing_venue_observation", "missing_benchmark", "source_conflict", or "no_exact_threshold_observation"; it is null only when status is available. Unavailable means every applicable route was attempted and failed; an incomplete route cannot claim exhaustion. Audit metadata is explainability only and must not supply or alter evidence. For every candidate_market record, verify the exact candidate key, supporting_only key, support side, threshold, venue requirement and benchmark requirement from the canonical matrix. If any one is absent, conflicting or unsupported, omit that candidate_market record. Never emit partial candidate evidence. Both home and away candidates need reciprocal support in the opposite team’s evidence array.

STRICT ANALYSISPACK V1 ENVELOPE CONTRACT (AnalysisPack has exactly these five top-level fields and no additional properties):
{
  "packName": "AnalysisPack v1",
  "schemaVersion": "1.0.0",
  "generatedAt": "ISO UTC timestamp ending in Z",
  "fixturePack": { ...FixturePack v1.0.0... },
  "researchPack": { ...ResearchPack v1.5.0... }
}
fixturePack and researchPack are nested objects, not sibling loose JSON fragments. ResearchPack.fixturePackRef must exactly match fixturePack.schemaVersion and fixturePack.fixtureDate. ResearchPack.marketResearchAudit is at $.researchPack.marketResearchAudit. For a no-fixture result, the nested FixturePack, ResearchPack fixture array, benchmark array and audit array follow the EMPTY-FIXTURE CONTRACT below.

STRICT V1.5 TOP-LEVEL RESEARCHPACK SKELETON (ResearchPack has exactly nine top-level fields; these are the only top-level fields and additional properties are forbidden):
{ "packName": "ResearchPack v1", "schemaVersion": "1.5.0", "fixturePackRef": { "schemaVersion": "1.0.0", "fixtureDate": "2026-01-01" }, "generatedAt": "2026-01-01T00:00:00Z", "dataStatus": "real", "sources": [], "competitionBenchmarks": [], "marketResearchAudit": [], "fixtures": [] }

STRICT V1.5 RESEARCH FIXTURE SKELETON (an item at ResearchPack.fixtures[] / $.researchPack.fixtures[]; these are the only fixture fields, additional properties are forbidden, and derived1x2FromGoals is omitted unless valid):
{ "fixtureId": "fixture-id", "competition": "Premier League", "homeTeam": "Home Team", "awayTeam": "Away Team", "homeEvidence": { "currentSeasonForm": { "summary": "Sourced summary", "lastFive": null, "lastTen": null, "homeOrAway": null, "goalsScored": null, "goalsConceded": null, "sourceIds": ["declared-source-id"] }, "marketHitRates": [], "optionalMetrics": {}, "currentSeasonLeagueMatches": 0 }, "awayEvidence": { "currentSeasonForm": { "summary": "Sourced summary", "lastFive": null, "lastTen": null, "homeOrAway": null, "goalsScored": null, "goalsConceded": null, "sourceIds": ["declared-source-id"] }, "marketHitRates": [], "optionalMetrics": {}, "currentSeasonLeagueMatches": 0 }, "derived1x2FromGoals": { "strategy": "derived_1x2_from_goals", "home": { "matchesPlayed": 2, "goalsScored": 0, "goalsConceded": 0, "sourceIds": ["declared-source-id"] }, "away": { "matchesPlayed": 2, "goalsScored": 0, "goalsConceded": 0, "sourceIds": ["declared-source-id"] }, "competitionCompletedFixtures": 1, "competitionPerTeamGoals": 1, "competitionSourceIds": ["declared-source-id"], "sourceConflict": false }, "opponentStrength": { "status": "unknown", "impact": "unknown", "detail": null, "sourceIds": ["declared-source-id"] }, "teamNews": { "status": "unknown", "impact": "unknown", "scope": "both", "application": "descriptive_only", "detail": null, "sourceIds": ["declared-source-id"] }, "fixtureCongestion": { "status": "unknown", "impact": "unknown", "scope": "both", "application": "descriptive_only", "detail": null, "sourceIds": ["declared-source-id"] }, "managerialContext": { "status": "unknown", "impact": "unknown", "scope": "both", "application": "descriptive_only", "detail": null, "sourceIds": ["declared-source-id"] }, "reasonsFor": [], "reasonsAgainst": [], "dataQuality": "insufficient" }

OPTIONAL DERIVED INPUT CONTRACT: The exact location is ResearchPack.fixtures[].derived1x2FromGoals (JSON path $.researchPack.fixtures[].derived1x2FromGoals inside AnalysisPack). When present it is exactly the object rendered in the fixture skeleton: all of strategy, home, away, competitionCompletedFixtures, competitionPerTeamGoals, competitionSourceIds, and sourceConflict are required; additional properties are forbidden. Each home and away object requires matchesPlayed (integer 2–5), goalsScored (non-negative integer), goalsConceded (non-negative integer), and sourceIds (non-empty unique declared IDs), with no additional properties except optional venue. The rolling inputs must use the current most-recent min(5, currentSeasonLeagueMatches) completed league fixtures. Optional home.venue and away.venue are each exactly { "matchesPlayed": 1, "goalsScored": 0, "goalsConceded": 0, "sourceIds": ["declared-source-id"] }, require every shown field, forbid additional properties, use non-negative integer goal totals and an integer matchesPlayed >= 1, and may be included only when sourced; FormFirst applies venue data only at its existing two-match minimum. competitionCompletedFixtures is an integer >= 1; competitionPerTeamGoals is a number > 0; competitionSourceIds is a non-empty unique array of declared IDs; sourceConflict must be false. If any required input is missing or conflicting, omit derived1x2FromGoals entirely. ChatGPT Search supplies only these sourced inputs. FormFirst—not ChatGPT Search—calculates the seven Poisson-derived result outputs (home win, draw, away win, home or draw, away or draw, home draw no bet, and away draw no bet); do not emit those outputs in ResearchPack.

EMPTY-FIXTURE CONTRACT: When fixture discovery finds no matches, emit FixturePack.fixtures: [], ResearchPack.fixtures: [], ResearchPack.competitionBenchmarks: [], and ResearchPack.marketResearchAudit: []. Do not fabricate sources, benchmarks, audits, or fixture evidence. Return the complete strict AnalysisPack envelope so FormFirst can import the no-fixture result. The app must show exactly “No scheduled fixtures for the selected date and competitions” and must not offer analysis generation. This is the sole exception to the normal one-audit-per-family and populated-research-array requirements.

OUTPUT INTEGRITY AND SOURCE CONTRACT: Emit only the requested strict JSON. ResearchPack has exactly nine top-level fields: packName, schemaVersion, fixturePackRef, generatedAt, dataStatus, sources, competitionBenchmarks, marketResearchAudit, and fixtures. Include one matching research fixture per supplied/discovered fixture, including insufficient fixtures. Sources contain exactly { "sourceId": "non-empty kebab-case string", "url": "absolute HTTPS URL with a hostname", "title": "non-empty string", "retrievedAt": "actual ISO 8601 UTC timestamp ending in Z" }; sourceId matches ^[a-z0-9]+(?:-[a-z0-9]+)*$, is the only ID field, and every populated component cites declared sourceIds. Encode URL slashes as \\u002F in emitted JSON (for example "https:\\u002F\\u002Fwww.soccerstats.com\\u002Ftable.asp?league=england"); never emit Markdown links or apply a domain allowlist. Use the most recent min(5, currentSeasonLeagueMatches) completed current-season league matches for every candidate, support, venue and derived-goal input. Use all available when fewer than five; two-to-four is usable_partial and cannot be Strong. Competition benchmarks use all completed current-season fixtures. Use direct source pages and completed current-season league data only—no cups, friendlies, older matches outside the window, or prior seasons. For cards manually count total over 2.5/3.5 and team over 0.5/1.5; for shots count team 8+/10+; for shots on target count team 3+/4+. competitionBenchmarks contain currentSeasonCompletedFixtures, marketBenchmarks, and optionalMetrics; benchmarks carry the exact candidate marketKey, marketGroup, selectionLabel, threshold, sampleSize, hits, supportPercent, and sourceIds. supporting_only records never become candidates. Unknown evidence remains absent/null/unknown only where the schema permits. Manual availability controls are settlement metadata, not evidence. “Unavailable” means the full source route was attempted, never “not researched.” Coverage diagnostics remain model-owned: identify the first cause as missing candidate evidence, missing supporting-only evidence, missing required venue evidence, missing matching benchmark, source conflict, or no exact source-backed threshold observations; distinguish team_to_score threshold 0.5, team_goals threshold 1.5/2.5, and total_goals threshold 1.5/2.5.

SCOPED CONTEXT: Retain v1.2 teamNews, fixtureCongestion, and managerialContext with home/away/both scope and descriptive_only/candidate_penalty application. Only known, current, sourced, candidate-relevant caution/material disruption may be candidate_penalty. Generic, unknown, neutral, positive, descriptive, non-directional, transfer, manager-change, or squad-turnover context without current candidate-relevant disruption is descriptive_only and has no numerical effect. opponentStrength is descriptive context.`;
