import { MARKET_CONTRACT, MARKET_FAMILY_CONTRACT } from './marketContract';

export const CANONICAL_MARKET_MATRIX = MARKET_FAMILY_CONTRACT;

const marketMatrix = MARKET_FAMILY_CONTRACT.map(({ marketGroup, label }, index) => {
  const variants = MARKET_CONTRACT.filter(item => item.marketGroup === marketGroup)
  return `${index + 1}. ${label} [${marketGroup}] — ${variants.map(item => `${item.marketKey}: threshold ${item.threshold ?? 'null'}; selectionLabel \`${item.selectionLabel.template}\`; supporting_only ${item.support.map(rule => `${rule.location} ${rule.marketKey} (${rule.marketGroup}, threshold ${rule.threshold ?? 'null'}, selectionLabel \`${rule.selectionLabel.template}\`)`).join(' + ')}; candidate sides ${item.candidateTeamSide.join('/')}; ${item.venueRequired ? 'required venue evidence' : 'venue evidence not required'}; exact same-marketKey/same-threshold competition benchmark ${item.benchmark.marketKey}; source route ${item.sourceRoute}; prohibited ${item.prohibitedSubstitutions.join(', ')}`).join(' | ')}`
}).join("\n");

export const RESEARCH_ACQUISITION_POLICY = `SOURCE HIERARCHY (apply per evidence component; fall back only when the earlier provider does not expose that exact value):
1. Official Premier League / EFL fixture pages — fixture and kick-off verification only, except an official completed-match centre may evidence an exact numeric team-level statistic.
2. FootyStats current-season league/team/statistics pages — preferred aggregate source; use only exact current-season values or exact counts manually derived from a completed-match table, never its prediction, betting-system, tip, odds, or bookmaker material.
3. SoccerStats current-season league/team/home/away/statistics pages — exact-component aggregate fallback when FootyStats lacks that value. An average alone is never sufficient; require explicit hit counts/percentages or an exactly countable completed-match table.
4. StatBunker current-season competition/club pages — only valid team-level current-season discipline evidence; never aggregate player statistics.
5. Specialist raw statistics from direct completed-match pages, in order: FotMob → SofaScore → official Premier League/EFL completed-match centre. Use only visibly exposed numeric team-level statistics.
6. WhoScored — Premier League-only fallback for team shots and shots on target, using exact current-season team-level or completed-match values only.
7. PROHIBITED: WinDrawWin, Flashscore, bookmaker, tipster, prediction, odds, player aggregation, proxy, average-only, inferred evidence, referee trends, xG substitutes, possession, and narrative reports.

NO DOUBLE HANDLING: Assign one source owner to each individual evidence component. Candidate, supporting-only, venue, and benchmark components may have different owners because they are distinct. Once a valid source supplies a component, do not collect a fallback duplicate; never combine, average, merge, or double-count the same team/metric/sample. If providers conflict on the exact current-season metric and scope, do not choose or average: isolate the conflict, omit only the affected candidate, and report source conflict; independent markets remain eligible.

PRIVATE RESEARCH WORKFLOW (complete before JSON):
A. Create a private checklist for every fixture and its completed current-season league matches.
B. Attempt every matrix family independently; finding one family never satisfies or ends another family’s research.
C. Collect explicit current-season league threshold observations, manually counting only verified completed-match tables where necessary.
D. For every proposed candidate verify exact candidate evidence, mandatory supporting_only opponent evidence, required venue evidence where the matrix says required, an exact same-marketKey/same-threshold competition benchmark, and declared citations.
E. Omit the candidate-market record when any mandatory component is missing, conflicting, not team-level, not current-season league-only, or average/proxy/inferred. Never substitute between market groups or thresholds and never insert a neutral value.

CANONICAL MARKET MATRIX (exactly 14 families; attempt every row independently and omit a candidate_market record if any mandatory component cannot be sourced):
selectionLabel is contract data, not prose. For every record, emit the exact label shown in this matrix, replacing only the {team} placeholder with the record's exact homeTeam or awayTeam. Do not replace a static label with a team name or paraphrase it.
${marketMatrix}

MANDATORY PRIVATE PRE-OUTPUT AUDIT (do not emit an audit field): For every candidate_market record, verify the exact candidate key, supporting_only key, support side, threshold, venue requirement and benchmark requirement from the canonical matrix. If any one is absent, conflicting or unsupported, omit that candidate_market record. Never emit partial candidate evidence. Both home and away candidates need reciprocal support in the opposite team’s evidence array.\n\nOUTPUT INTEGRITY AND SOURCE CONTRACT: Emit only the requested strict JSON. ResearchPack requires packName, schemaVersion, fixturePackRef, actual UTC generatedAt, dataStatus real, sources, competitionBenchmarks, and one matching research fixture per supplied/discovered fixture, including insufficient fixtures. Sources contain exactly { "sourceId": "non-empty kebab-case string", "url": "absolute HTTPS URL with a hostname", "title": "non-empty string", "retrievedAt": "actual ISO 8601 UTC timestamp ending in Z" }; sourceId matches ^[a-z0-9]+(?:-[a-z0-9]+)*$, is the only ID field, and every populated component cites declared sourceIds. Encode URL slashes as \\u002F in emitted JSON (for example "https:\\u002F\\u002Fwww.soccerstats.com\\u002Ftable.asp?league=england"); never emit Markdown links or apply a domain allowlist. Use direct source pages and completed current-season league data only—no cups, friendlies, or prior seasons. competitionBenchmarks contain currentSeasonCompletedFixtures, marketBenchmarks, and optionalMetrics; benchmarks carry the exact candidate marketKey, marketGroup, selectionLabel, threshold, sampleSize, hits, supportPercent, and sourceIds. supporting_only records never become candidates. Unknown evidence remains absent/null/unknown only where the schema permits. Manual availability controls are settlement metadata, not evidence. “Unavailable” means the full source route was attempted, never “not researched.” Coverage diagnostics remain model-owned: identify the first cause as missing candidate evidence, missing supporting-only evidence, missing required venue evidence, missing matching benchmark, source conflict, or no exact source-backed threshold observations; distinguish team_to_score threshold 0.5, team_goals threshold 1.5/2.5, and total_goals threshold 1.5/2.5.

SCOPED CONTEXT: Retain v1.2 teamNews, fixtureCongestion, and managerialContext with home/away/both scope and descriptive_only/candidate_penalty application. Only known, current, sourced, candidate-relevant caution/material disruption may be candidate_penalty. Generic, unknown, neutral, positive, descriptive, non-directional, transfer, manager-change, or squad-turnover context without current candidate-relevant disruption is descriptive_only and has no numerical effect. opponentStrength is descriptive context.`;
