import { SUPPORTED_COMPETITIONS, type FixturePack, type FreshnessOptions, type ResearchPack, type SavedAnalysisRun, type ValidationIssue, type ValidationResult } from './types'

const datePattern = /^\d{4}-\d{2}-\d{2}$/
const timePattern = /^(?:[01]\d|2[0-3]):[0-5]\d$/
const prohibited: [string, RegExp][] = [
  ['odds', /\bodds\b/i], ['price', /\bprices?\b/i], ['implied probability', /\bimplied probability\b/i],
  ['payout', /\bpayouts?\b/i], ['expected value', /\bexpected value\b/i], ['value betting', /\bvalue bet(?:ting)?\b/i],
  ['bookmaker', /\bbookmakers?\b/i], ['betting link', /\bbetting links?\b/i], ['tipster', /\btipsters?\b/i], ['stake', /\bstakes?\b/i],
]
const issue = (code: string, path: string, message: string): ValidationIssue => ({ code, path, message })
const record = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value)
const timestamp = (value: unknown) => typeof value === 'string' && /T/.test(value) && Number.isFinite(Date.parse(value))
const date = (value: unknown) => typeof value === 'string' && datePattern.test(value) && !Number.isNaN(Date.parse(`${value}T00:00:00Z`))
const finish = <T>(value: unknown, errors: ValidationIssue[], warnings: ValidationIssue[]): ValidationResult<T> => errors.length ? { valid: false, errors, warnings } : { valid: true, data: value as T, errors, warnings }
function identity(value: unknown, name: string, errors: ValidationIssue[]) {
  if (!record(value)) { errors.push(issue('invalid_type', '$', 'Expected a JSON object.')); return false }
  if (value.packName !== name) errors.push(issue('invalid_pack_name', '$.packName', `Expected ${name}.`))
  if (value.schemaVersion !== '1.0.0') errors.push(issue('unsupported_version', '$.schemaVersion', 'Expected schema version 1.0.0.'))
  return true
}
function duplicateIds(items: unknown[], path: string, errors: ValidationIssue[]) {
  const seen = new Set<string>(); items.forEach((item, index) => { const id = record(item) ? item.fixtureId : undefined; if (typeof id === 'string' && seen.has(id)) errors.push(issue('duplicate_id', `${path}[${index}].fixtureId`, `Duplicate fixture ID: ${id}.`)); if (typeof id === 'string') seen.add(id) })
}
export function parseJson(input: string): ValidationResult<unknown> { try { return { valid: true, data: JSON.parse(input), errors: [], warnings: [] } } catch { return { valid: false, errors: [issue('invalid_json', '$', 'Input is not valid JSON.')], warnings: [] } } }
export function validateFixturePack(value: unknown): ValidationResult<FixturePack> {
  const errors: ValidationIssue[] = [], warnings: ValidationIssue[] = []; if (!identity(value, 'FixturePack v1', errors)) return finish(value, errors, warnings)
  const v = value as Record<string, unknown>
  if (!date(v.fixtureDate)) errors.push(issue('invalid_date', '$.fixtureDate', 'Fixture date must be a valid ISO date.'))
  if (!timestamp(v.generatedAt)) errors.push(issue('invalid_timestamp', '$.generatedAt', 'Generated timestamp is invalid.'))
  if (!Array.isArray(v.competitions) || v.competitions.length === 0) errors.push(issue('missing_competitions', '$.competitions', 'At least one competition is required.'))
  else { const seen = new Set(); v.competitions.forEach((c, i) => { if (!SUPPORTED_COMPETITIONS.includes(c as never)) errors.push(issue('unsupported_competition', `$.competitions[${i}]`, `Unsupported competition: ${String(c)}.`)); if (seen.has(c)) errors.push(issue('duplicate_competition', `$.competitions[${i}]`, 'Competitions must be unique.')); seen.add(c) }) }
  if (!Array.isArray(v.fixtures) || v.fixtures.length === 0) errors.push(issue('empty_fixtures', '$.fixtures', 'At least one fixture is required.'))
  else { duplicateIds(v.fixtures, '$.fixtures', errors); v.fixtures.forEach((f, i) => { if (!record(f)) return errors.push(issue('invalid_fixture', `$.fixtures[${i}]`, 'Fixture must be an object.')); if (!SUPPORTED_COMPETITIONS.includes(f.competition as never)) errors.push(issue('unsupported_competition', `$.fixtures[${i}].competition`, 'Fixture competition is unsupported.')); if (typeof f.homeTeam !== 'string' || !f.homeTeam.trim() || typeof f.awayTeam !== 'string' || !f.awayTeam.trim()) errors.push(issue('empty_team', `$.fixtures[${i}]`, 'Both teams must be non-empty.')); else if (f.homeTeam.trim().toLowerCase() === f.awayTeam.trim().toLowerCase()) errors.push(issue('identical_teams', `$.fixtures[${i}]`, 'Home and away teams must differ.')); const k = f.kickOff; if (!record(k) || !timestamp(k.utc) || !date(k.localDate) || typeof k.localTime !== 'string' || !timePattern.test(k.localTime) || k.timezone !== 'Europe/London') errors.push(issue('invalid_kickoff', `$.fixtures[${i}].kickOff`, 'Kick-off must contain a valid UTC timestamp, local date/time and Europe/London timezone.')) }) }
  return finish(value, errors, warnings)
}
function scanStrings(value: unknown, path: string, errors: ValidationIssue[]) { if (typeof value === 'string') prohibited.forEach(([category, regex]) => { if (regex.test(value)) errors.push(issue('prohibited_content', path, `Prohibited category detected: ${category}.`)) }); else if (Array.isArray(value)) value.forEach((x, i) => scanStrings(x, `${path}[${i}]`, errors)); else if (record(value)) Object.entries(value).forEach(([k, x]) => scanStrings(x, `${path}.${k}`, errors)) }
export function validateResearchPack(value: unknown, fixturePack?: FixturePack, freshness?: FreshnessOptions): ValidationResult<ResearchPack> {
  const errors: ValidationIssue[] = [], warnings: ValidationIssue[] = []; if (!identity(value, 'ResearchPack v1', errors)) return finish(value, errors, warnings); const v = value as Record<string, unknown>; scanStrings(v, '$', errors)
  if (!timestamp(v.generatedAt)) errors.push(issue('invalid_timestamp', '$.generatedAt', 'Generated timestamp is invalid.'))
  if (v.dataStatus !== 'synthetic' && v.dataStatus !== 'real') errors.push(issue('invalid_data_status', '$.dataStatus', 'Data status must be synthetic or real.')); else if (v.dataStatus === 'synthetic') warnings.push(issue('synthetic_data', '$.dataStatus', 'Synthetic test data must not be used for real analysis.'))
  const sources = Array.isArray(v.sources) ? v.sources : []; if (!sources.length) errors.push(issue('missing_sources', '$.sources', 'At least one source is required.')); const sourceIds = new Set<string>(); sources.forEach((s, i) => { if (!record(s) || typeof s.sourceId !== 'string' || !s.sourceId || typeof s.title !== 'string' || !s.title || typeof s.url !== 'string' || !/^https:\/\/[^\s]+$/i.test(s.url) || !timestamp(s.retrievedAt)) errors.push(issue('invalid_source', `$.sources[${i}]`, 'Source requires ID, title, HTTPS URL and valid retrieval timestamp.')); else { if (sourceIds.has(s.sourceId)) errors.push(issue('duplicate_source', `$.sources[${i}].sourceId`, 'Source IDs must be unique.')); sourceIds.add(s.sourceId); if (freshness) { const age = Date.parse(freshness.referenceTimestamp) - Date.parse(s.retrievedAt as string); if (!timestamp(freshness.referenceTimestamp) || freshness.maximumAgeHours < 0) errors.push(issue('invalid_freshness_settings', '$', 'Freshness settings are invalid.')); else if (age > freshness.maximumAgeHours * 3_600_000) errors.push(issue('stale_source', `$.sources[${i}].retrievedAt`, 'Source exceeds the configured maximum age.')) } } })
  const fixtures = Array.isArray(v.fixtures) ? v.fixtures : []; if (!fixtures.length) errors.push(issue('missing_evidence', '$.fixtures', 'Research evidence is required.')); duplicateIds(fixtures, '$.fixtures', errors)
  fixtures.forEach((rf, i) => { if (!record(rf) || !record(rf.homeEvidence) || !record(rf.awayEvidence) || !record(rf.opponentStrength) || !record(rf.teamNews) || !record(rf.fixtureCongestion) || !record(rf.managerialContext)) errors.push(issue('missing_evidence', `$.fixtures[${i}]`, 'Mandatory team and context evidence is missing.')); if (fixturePack && record(rf)) { const match = fixturePack.fixtures.find(f => f.fixtureId === rf.fixtureId); if (!match || match.competition !== rf.competition || match.homeTeam !== rf.homeTeam || match.awayTeam !== rf.awayTeam) errors.push(issue('fixture_mismatch', `$.fixtures[${i}]`, 'Research fixture does not match the referenced fixture pack.')) } })
  const checkCitations = (x: unknown, path: string) => { if (record(x) && 'sourceIds' in x) { if (!Array.isArray(x.sourceIds) || x.sourceIds.length === 0) errors.push(issue('missing_source_citation', `${path}.sourceIds`, 'Populated evidence requires at least one source citation.')); else x.sourceIds.forEach((id, i) => { if (typeof id !== 'string' || !sourceIds.has(id)) errors.push(issue('unknown_source_citation', `${path}.sourceIds[${i}]`, `Unknown source ID: ${String(id)}.`)) }) } if (Array.isArray(x)) x.forEach((n, i) => checkCitations(n, `${path}[${i}]`)); else if (record(x)) Object.entries(x).forEach(([k, n]) => checkCitations(n, `${path}.${k}`)) }; checkCitations(v.fixtures, '$.fixtures')
  const walkNumbers = (x: unknown, path: string) => { if (typeof x === 'number' && (!Number.isFinite(x) || x < 0 || x > 10000)) errors.push(issue('implausible_number', path, 'Numeric evidence is obviously implausible.')); else if (Array.isArray(x)) x.forEach((n, i) => walkNumbers(n, `${path}[${i}]`)); else if (record(x)) Object.entries(x).forEach(([k, n]) => walkNumbers(n, `${path}.${k}`)) }; walkNumbers(v.fixtures, '$.fixtures')
  return finish(value, errors, warnings)
}
export function validateSavedAnalysisRun(value: unknown): ValidationResult<SavedAnalysisRun> { const errors: ValidationIssue[] = [], warnings: ValidationIssue[] = []; if (!identity(value, 'SavedAnalysisRun v1', errors)) return finish(value, errors, warnings); const v = value as Record<string, unknown>; if (!timestamp(v.createdAt)) errors.push(issue('invalid_timestamp', '$.createdAt', 'Created timestamp is invalid.')); if (v.dataStatus === 'synthetic') warnings.push(issue('synthetic_data', '$.dataStatus', 'Synthetic test run must not be treated as real analysis.')); if (!record(v.settings) || v.settings.deterministic !== true || !timestamp(v.settings.referenceTimestamp) || typeof v.settings.maximumSourceAgeHours !== 'number') errors.push(issue('invalid_settings', '$.settings', 'Deterministic settings are invalid.')); for (const key of ['fixturePackRef','researchPackRef','validation']) if (!record(v[key])) errors.push(issue('missing_field', `$.${key}`, `${key} is required.`)); for (const key of ['candidates','builders','results']) if (!Array.isArray(v[key])) errors.push(issue('missing_field', `$.${key}`, `${key} must be an array.`)); scanStrings(v, '$', errors); return finish(value, errors, warnings) }
