import { MARKET_GROUPS, SUPPORTED_COMPETITIONS, type FixturePack, type FreshnessOptions, type ResearchPack, type SavedAnalysisRun, type ValidationIssue, type ValidationResult } from './types'

const datePattern = /^\d{4}-\d{2}-\d{2}$/
const timePattern = /^(?:[01]\d|2[0-3]):[0-5]\d$/
const prohibited: [string, RegExp][] = [
  ['odds', /\bodds\b/i], ['price', /\bprices?\b/i], ['implied probability', /\bimplied probability\b/i],
  ['payout', /\bpayouts?\b/i], ['expected value', /\bexpected value\b/i], ['value betting', /\bvalue bet(?:ting)?\b/i],
  ['bookmaker', /\bbookmakers?\b/i], ['betting link', /\bbetting links?\b/i], ['tipster', /\btipsters?\b/i], ['stake', /\bstakes?\b/i],
]
const issue = (code: string, path: string, message: string): ValidationIssue => ({ code, path, message })
const record = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value)
const timestamp = (value: unknown) => typeof value === 'string' && /T/.test(value) && Number.isFinite(Date.parse(value))
const date = (value: unknown) => typeof value === 'string' && datePattern.test(value) && !Number.isNaN(Date.parse(`${value}T00:00:00Z`))
const finish = <T>(value: unknown, errors: ValidationIssue[], warnings: ValidationIssue[]): ValidationResult<T> => errors.length ? { valid: false, errors, warnings } : { valid: true, data: value as T, errors, warnings }
function identity(value: unknown, name: string, errors: ValidationIssue[]) {
  if (!record(value)) { errors.push(issue('invalid_type', '$', 'Expected a JSON object.')); return false }
  if (value.packName !== name) errors.push(issue('invalid_pack_name', '$.packName', `Expected ${name}.`))
  if (value.schemaVersion !== '1.0.0') errors.push(issue('unsupported_version', '$.schemaVersion', 'Expected schema version 1.0.0.'))
  return true
}
function duplicateIds(items: unknown[], path: string, errors: ValidationIssue[]) {
  const seen = new Set<string>(); items.forEach((item, index) => { const id = record(item) ? item.fixtureId : undefined; if (typeof id === 'string' && seen.has(id)) errors.push(issue('duplicate_id', `${path}[${index}].fixtureId`, `Duplicate fixture ID: ${id}.`)); if (typeof id === 'string') seen.add(id) })
}
export function parseJson(input: string): ValidationResult<unknown> { try { return { valid: true, data: JSON.parse(input), errors: [], warnings: [] } } catch { return { valid: false, errors: [issue('invalid_json', '$', 'Input is not valid JSON.')], warnings: [] } } }
export function validateFixturePack(value: unknown): ValidationResult<FixturePack> {
  const errors: ValidationIssue[] = [], warnings: ValidationIssue[] = []; if (!identity(value, 'FixturePack v1', errors)) return finish(value, errors, warnings)
  const v = value as Record<string, unknown>
  if (!date(v.fixtureDate)) errors.push(issue('invalid_date', '$.fixtureDate', 'Fixture date must be a valid ISO date.'))
  if (!timestamp(v.generatedAt)) errors.push(issue('invalid_timestamp', '$.generatedAt', 'Generated timestamp is invalid.'))
  if (!Array.isArray(v.competitions) || v.competitions.length === 0) errors.push(issue('missing_competitions', '$.competitions', 'At least one competition is required.'))
  else { const seen = new Set(); v.competitions.forEach((c, i) => { if (!SUPPORTED_COMPETITIONS.includes(c as never)) errors.push(issue('unsupported_competition', `$.competitions[${i}]`, `Unsupported competition: ${String(c)}. FormFirst supports only Premier League and Championship.`)); if (seen.has(c)) errors.push(issue('duplicate_competition', `$.competitions[${i}]`, 'Competitions must be unique.')); seen.add(c) }) }
  if (!Array.isArray(v.fixtures)) errors.push(issue('invalid_fixtures', '$.fixtures', 'Fixtures must be an array.'))
  else { duplicateIds(v.fixtures, '$.fixtures', errors); v.fixtures.forEach((f, i) => { if (!record(f)) return errors.push(issue('invalid_fixture', `$.fixtures[${i}]`, 'Fixture must be an object.')); if (!SUPPORTED_COMPETITIONS.includes(f.competition as never)) errors.push(issue('unsupported_competition', `$.fixtures[${i}].competition`, `Unsupported competition: ${String(f.competition)}. FormFirst supports only Premier League and Championship.`)); else if (!Array.isArray(v.competitions) || !v.competitions.includes(f.competition)) errors.push(issue('competition_not_selected', `$.fixtures[${i}].competition`, 'Fixture competition must appear in the pack competitions.')); if (typeof f.homeTeam !== 'string' || !f.homeTeam.trim() || typeof f.awayTeam !== 'string' || !f.awayTeam.trim()) errors.push(issue('empty_team', `$.fixtures[${i}]`, 'Both teams must be non-empty.')); else if (f.homeTeam.trim().toLowerCase() === f.awayTeam.trim().toLowerCase()) errors.push(issue('identical_teams', `$.fixtures[${i}]`, 'Home and away teams must differ.')); const k = f.kickOff; if (!record(k) || !timestamp(k.utc) || !date(k.localDate) || typeof k.localTime !== 'string' || !timePattern.test(k.localTime) || k.timezone !== 'Europe/London') errors.push(issue('invalid_kickoff', `$.fixtures[${i}].kickOff`, 'Kick-off must contain a valid UTC timestamp, local date/time and Europe/London timezone.')); else if (k.localDate !== v.fixtureDate) errors.push(issue('fixture_date_mismatch', `$.fixtures[${i}].kickOff.localDate`, 'Fixture local date must match the pack fixture date.')) }) }
  return finish(value, errors, warnings)
}
function scanStrings(value: unknown, path: string, errors: ValidationIssue[]) { if (typeof value === 'string') prohibited.forEach(([category, regex]) => { if (regex.test(value)) errors.push(issue('prohibited_content', path, `Prohibited category detected: ${category}.`)) }); else if (Array.isArray(value)) value.forEach((x, i) => scanStrings(x, `${path}[${i}]`, errors)); else if (record(value)) Object.entries(value).forEach(([k, x]) => scanStrings(x, `${path}.${k}`, errors)) }
export function validateResearchPack(value: unknown, fixturePack?: FixturePack, freshness?: FreshnessOptions): ValidationResult<ResearchPack> {
  const errors: ValidationIssue[] = [], warnings: ValidationIssue[] = []; if (!identity(value, 'ResearchPack v1', errors)) return finish(value, errors, warnings); const v = value as Record<string, unknown>; scanStrings(v, '$', errors)
  if (!timestamp(v.generatedAt)) errors.push(issue('invalid_timestamp', '$.generatedAt', 'Generated timestamp is invalid.'))
  if (v.dataStatus !== 'synthetic' && v.dataStatus !== 'real') errors.push(issue('invalid_data_status', '$.dataStatus', 'Data status must be synthetic or real.')); else if (v.dataStatus === 'synthetic') warnings.push(issue('synthetic_data', '$.dataStatus', 'Synthetic test data must not be used for real analysis.'))
  const sources = Array.isArray(v.sources) ? v.sources : []; if (!sources.length) errors.push(issue('missing_sources', '$.sources', 'At least one source is required.')); const sourceIds = new Set<string>(); sources.forEach((s, i) => { if (!record(s) || typeof s.sourceId !== 'string' || !s.sourceId || typeof s.title !== 'string' || !s.title || typeof s.url !== 'string' || !/^https:\/\/[^\s]+$/i.test(s.url) || !timestamp(s.retrievedAt)) errors.push(issue('invalid_source', `$.sources[${i}]`, 'Source requires ID, title, HTTPS URL and valid retrieval timestamp.')); else { if (sourceIds.has(s.sourceId)) errors.push(issue('duplicate_source', `$.sources[${i}].sourceId`, 'Source IDs must be unique.')); sourceIds.add(s.sourceId); if (freshness) { const age = Date.parse(freshness.referenceTimestamp) - Date.parse(s.retrievedAt as string); if (!timestamp(freshness.referenceTimestamp) || !Number.isFinite(freshness.maximumAgeHours) || freshness.maximumAgeHours < 0) errors.push(issue('invalid_freshness_settings', '$', 'Freshness settings are invalid.')); else if (age < 0) errors.push(issue('future_source', `$.sources[${i}].retrievedAt`, 'Source retrieval timestamp is later than the freshness reference timestamp.')); else if (age > freshness.maximumAgeHours * 3_600_000) errors.push(issue('stale_source', `$.sources[${i}].retrievedAt`, 'Source exceeds the configured maximum age.')) } } })
  const fixtures = Array.isArray(v.fixtures) ? v.fixtures : []; if (!fixtures.length) errors.push(issue('missing_evidence', '$.fixtures', 'Research evidence is required.')); duplicateIds(fixtures, '$.fixtures', errors)
  fixtures.forEach((rf, i) => { if (record(rf) && !SUPPORTED_COMPETITIONS.includes(rf.competition as never)) errors.push(issue('unsupported_competition', `$.fixtures[${i}].competition`, `Unsupported competition: ${String(rf.competition)}. FormFirst supports only Premier League and Championship.`)); if (!record(rf) || !record(rf.homeEvidence) || !record(rf.awayEvidence) || !record(rf.opponentStrength) || !record(rf.teamNews) || !record(rf.fixtureCongestion) || !record(rf.managerialContext)) errors.push(issue('missing_evidence', `$.fixtures[${i}]`, 'Mandatory team and context evidence is missing.')); if (record(rf)) { for (const context of ['opponentStrength', 'teamNews', 'fixtureCongestion', 'managerialContext']) { const item = rf[context]; if (!record(item) || !['positive','neutral','caution','material','unknown'].includes(String(item.impact))) errors.push(issue('invalid_context_impact', `$.fixtures[${i}].${context}.impact`, 'Context requires an explicit supported impact.')) } for (const side of ['homeEvidence', 'awayEvidence']) { const team = rf[side]; if (!record(team) || !record(team.currentSeasonForm) || !Array.isArray(team.marketHitRates) || team.marketHitRates.length === 0 || !record(team.optionalMetrics)) errors.push(issue('incomplete_evidence', `$.fixtures[${i}].${side}`, 'Team evidence must include form, market hit rates, and optional metrics.')); else team.marketHitRates.forEach((market, m) => { const path = `$.fixtures[${i}].${side}.marketHitRates[${m}]`; if (!record(market) || typeof market.marketKey !== 'string' || !/^[a-z0-9_]+$/.test(market.marketKey) || !MARKET_GROUPS.includes(market.marketGroup as never) || !['home','away','both','match'].includes(String(market.teamSide)) || typeof market.selectionLabel !== 'string' || !market.selectionLabel) errors.push(issue('invalid_market_evidence', path, 'Market evidence requires canonical identifiers and a team-level label.')); else for (const [hits, sample] of [['hits','sampleSize'], ['recentHits','recentSampleSize'], ['venueHits','venueSampleSize']] as const) if (market[hits] !== null && market[sample] !== null && (typeof market[hits] !== 'number' || typeof market[sample] !== 'number' || market[hits] > market[sample])) errors.push(issue('contradictory_market_evidence', `${path}.${hits}`, 'Hits cannot exceed the cited sample size.')) }) } } if (fixturePack && record(rf)) { const match = fixturePack.fixtures.find(f => f.fixtureId === rf.fixtureId); if (!match || match.competition !== rf.competition || match.homeTeam !== rf.homeTeam || match.awayTeam !== rf.awayTeam) errors.push(issue('fixture_mismatch', `$.fixtures[${i}]`, 'Research fixture does not match the referenced fixture pack.')) } })
  if (fixturePack) { if (!record(v.fixturePackRef) || v.fixturePackRef.schemaVersion !== fixturePack.schemaVersion || v.fixturePackRef.fixtureDate !== fixturePack.fixtureDate) errors.push(issue('fixture_pack_ref_mismatch', '$.fixturePackRef', 'Research pack reference does not match the current fixture pack.')); for (const fixture of fixturePack.fixtures) if (!fixtures.some(rf => record(rf) && rf.fixtureId === fixture.fixtureId)) errors.push(issue('missing_fixture', '$.fixtures', `Missing research fixture: ${fixture.fixtureId}.`)); for (const rf of fixtures) if (record(rf) && !fixturePack.fixtures.some(f => f.fixtureId === rf.fixtureId)) errors.push(issue('unexpected_fixture', '$.fixtures', `Unexpected research fixture: ${String(rf.fixtureId)}.`)) }
  const checkCitations = (x: unknown, path: string) => { if (record(x) && 'sourceIds' in x) { if (!Array.isArray(x.sourceIds) || x.sourceIds.length === 0) errors.push(issue('missing_source_citation', `${path}.sourceIds`, 'Populated evidence requires at least one source citation.')); else x.sourceIds.forEach((id, i) => { if (typeof id !== 'string' || !sourceIds.has(id)) errors.push(issue('unknown_source_citation', `${path}.sourceIds[${i}]`, `Unknown source ID: ${String(id)}.`)) }) } if (Array.isArray(x)) x.forEach((n, i) => checkCitations(n, `${path}[${i}]`)); else if (record(x)) Object.entries(x).forEach(([k, n]) => checkCitations(n, `${path}.${k}`)) }; checkCitations(v.fixtures, '$.fixtures')
  const walkNumbers = (x: unknown, path: string) => { if (typeof x === 'number' && (!Number.isFinite(x) || x < 0 || x > 10000)) errors.push(issue('implausible_number', path, 'Numeric evidence is obviously implausible.')); else if (Array.isArray(x)) x.forEach((n, i) => walkNumbers(n, `${path}[${i}]`)); else if (record(x)) Object.entries(x).forEach(([k, n]) => walkNumbers(n, `${path}.${k}`)) }; walkNumbers(v.fixtures, '$.fixtures')
  return finish(value, errors, warnings)
}
export function validateSavedAnalysisRun(value: unknown): ValidationResult<SavedAnalysisRun> {
  const errors: ValidationIssue[] = [], warnings: ValidationIssue[] = []
  if (!identity(value, 'SavedAnalysisRun v1', errors)) return finish(value, errors, warnings)
  const v = value as Record<string, unknown>
  if (typeof v.runId !== 'string' || !/^[A-Za-z0-9._-]{1,120}$/.test(v.runId)) errors.push(issue('invalid_run_id', '$.runId', 'Run ID must use 1–120 safe filename characters.'))
  if (!timestamp(v.createdAt) || !timestamp(v.generatedAt)) errors.push(issue('invalid_timestamp', '$', 'Created and generated timestamps are required.'))
  if (v.dataStatus !== 'real' && v.dataStatus !== 'synthetic') errors.push(issue('invalid_data_status', '$.dataStatus', 'Data status must be real or synthetic.'))
  else if (v.dataStatus === 'synthetic') warnings.push(issue('synthetic_data', '$.dataStatus', 'Synthetic test run must not be treated as real analysis.'))
  const settings = v.settings
  if (!record(settings) || settings.deterministic !== true || !timestamp(settings.referenceTimestamp) || typeof settings.maximumSourceAgeHours !== 'number' || settings.maximumSourceAgeHours < 0 || !record(settings.marketAvailability) || Object.keys(settings.marketAvailability).length !== MARKET_GROUPS.length || MARKET_GROUPS.some(group => !['unknown','available','unavailable'].includes(String((settings.marketAvailability as Record<string, unknown>)[group])))) errors.push(issue('invalid_settings', '$.settings', 'Deterministic settings and every market availability status are required.'))
  if (!record(v.analysisInputs) || !record(v.analysisInputs.fixturePack) || !record(v.analysisInputs.researchPack)) errors.push(issue('invalid_analysis_inputs', '$.analysisInputs', 'The exact FixturePack and ResearchPack inputs are required.'))
  else {
    const fixture = validateFixturePack(v.analysisInputs.fixturePack); const research = fixture.valid ? validateResearchPack(v.analysisInputs.researchPack, fixture.data) : validateResearchPack(v.analysisInputs.researchPack)
    errors.push(...fixture.errors.map(item => ({ ...item, path: `$.analysisInputs.fixturePack${item.path.slice(1)}` })), ...research.errors.map(item => ({ ...item, path: `$.analysisInputs.researchPack${item.path.slice(1)}` })))
    if (fixture.valid && research.valid && v.dataStatus !== research.data!.dataStatus) errors.push(issue('data_status_mismatch', '$.dataStatus', 'Run data status must match the research snapshot.'))
  }
  for (const key of ['fixturePackRef','researchPackRef','validation']) if (!record(v[key])) errors.push(issue('missing_field', `$.${key}`, `${key} is required.`))
  if (typeof v.modelVersion !== 'string' || !v.modelVersion) errors.push(issue('invalid_model_version', '$.modelVersion', 'Model version is required.'))
  if (!Array.isArray(v.candidates) || v.candidates.some(candidate => !record(candidate) || typeof candidate.id !== 'string' || typeof candidate.estimatedProbability !== 'number' || !record(candidate.supportingEvidence) || !record(candidate.correlation))) errors.push(issue('invalid_candidates', '$.candidates', 'Complete model candidates are required.'))
  if (!record(v.builders) || !record(v.builders.highProbability) || !record(v.builders.balanced) || v.builders.highProbability.kind !== 'high_probability' || v.builders.balanced.kind !== 'balanced') errors.push(issue('invalid_builders', '$.builders', 'Both complete builder outcomes are required.'))
  const results = v.results
  if (!record(results) || !record(results.builders) || !record(results.legs) || !record(results.builders.high_probability) || !record(results.builders.balanced)) errors.push(issue('invalid_results', '$.results', 'Manual outcomes for both builders and every selected leg are required.'))
  else {
    const entries = [...Object.entries(results.builders), ...Object.entries(results.legs)]
    for (const [id, outcome] of entries) if (!record(outcome) || !['pending','won','lost','void'].includes(String(outcome.outcome)) || (outcome.updatedAt !== null && !timestamp(outcome.updatedAt))) errors.push(issue('invalid_outcome', `$.results.${id}`, 'Outcome must be pending, won, lost or void with an optional update timestamp.'))
    const expectedLegs = new Set<string>(); if (record(v.builders)) for (const builder of [v.builders.highProbability, v.builders.balanced]) if (record(builder) && builder.status === 'builder' && Array.isArray(builder.selectedLegs)) for (const leg of builder.selectedLegs) if (record(leg) && typeof leg.id === 'string') expectedLegs.add(leg.id)
    const resultLegs = results.legs as Record<string, unknown>
    if (Object.keys(resultLegs).length !== expectedLegs.size || [...expectedLegs].some(id => !(id in resultLegs))) errors.push(issue('result_leg_mismatch', '$.results.legs', 'Manual leg outcomes must exactly match saved builder legs.'))
    if (results.updatedAt !== null && !timestamp(results.updatedAt)) errors.push(issue('invalid_timestamp', '$.results.updatedAt', 'Result update timestamp is invalid.'))
  }
  scanStrings({ candidates: v.candidates, builders: v.builders }, '$', errors)
  return finish(value, errors, warnings)
}
