import type { ChangeEvent } from 'react'
import { formatManualEntryList, SETTLEMENT_STATEMENT } from './domain/analysisPresentation'
import { downloadSavedRun } from './domain/savedRunBrowser'
import type { BuilderKind, BuilderOutcome, ManualOutcome, SavedAnalysisRun } from './domain/types'

const RESPONSIBLE = '18+; analysis only; only stake what you can afford to lose.'
interface Props { runs: SavedAnalysisRun[]; selected: SavedAnalysisRun | null; feedback: string; onOpen(id: string): void; onImport(file: File): void; onOutcome(target: { type: 'builder'; id: BuilderKind } | { type: 'leg'; id: string }, outcome: ManualOutcome): void }
const available = (builder: BuilderOutcome) => builder.status === 'builder' ? `Available (${builder.selectedLegs.length} legs)` : 'No qualifying builder today'
export default function SavedHistory({ runs, selected, feedback, onOpen, onImport, onOutcome }: Props) {
  const importFile = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (file) onImport(file); event.target.value = '' }
  const outcomeControl = (label: string, target: { type: 'builder'; id: BuilderKind } | { type: 'leg'; id: string }, value: ManualOutcome) => <label>{label}<select value={value} onChange={event => onOutcome(target, event.target.value as ManualOutcome)}><option value="pending">Pending</option><option value="won">Won</option><option value="lost">Lost</option><option value="void">Void</option></select></label>
  const builder = (title: string, kind: BuilderKind, value: BuilderOutcome) => <article className="builder-card"><h4>{title}</h4>{outcomeControl(`${title} manually recorded result`, { type: 'builder', id: kind }, selected!.results.builders[kind].outcome)}{value.status === 'no_qualifying_builder' ? <><p><strong>No qualifying builder today</strong></p><p>{value.reason}</p></> : <><p>Saved combined model probability: {value.estimatedCombinedProbability}% · {value.overallConfidence}</p><ul>{value.selectedLegs.map(leg => <li key={leg.id}>{leg.selectionLabel} {outcomeControl(`${leg.selectionLabel} manually recorded result`, { type: 'leg', id: leg.id }, selected!.results.legs[leg.id].outcome)}</li>)}</ul><h5>Correlation notes</h5><ul>{value.correlationNotes.length ? value.correlationNotes.map(note => <li key={note}>{note}</li>) : <li>No adjustment note generated.</li>}</ul><div className="manual-list"><h5>Saved manual-entry list</h5><pre>{formatManualEntryList(value, selected!.analysisInputs.fixturePack)}</pre></div></>}</article>
  return <section className="history" aria-labelledby="history-title"><p className="stage-number">Stage 07 · Local saved-run history</p><h2 id="history-title">Saved analysis history</h2><p>Runs are stored only in this browser and may be lost if its site data is cleared. Nothing is synced remotely.</p><label htmlFor="run-import">Import a SavedAnalysisRun v1 JSON file</label><input id="run-import" type="file" accept="application/json,.json" onChange={importFile}/><p role="status" aria-live="polite">{feedback}</p>{runs.length === 0 ? <p>No saved analyses in this browser.</p> : <div className="table-wrap"><table><caption>Local saved analyses</caption><thead><tr><th>Saved</th><th>Analysis date</th><th>Competitions</th><th>Fixtures</th><th>Model</th><th>Builders</th><th>Review</th></tr></thead><tbody>{runs.map(run => <tr key={run.runId}><td>{new Date(run.createdAt).toLocaleString()}</td><td>{run.analysisInputs.fixturePack.fixtureDate}</td><td>{run.analysisInputs.fixturePack.competitions.join(', ')}</td><td>{run.analysisInputs.fixturePack.fixtures.length}</td><td>{run.modelVersion}</td><td>High-probability: {available(run.builders.highProbability)}<br/>Balanced: {available(run.builders.balanced)}</td><td><button type="button" onClick={() => onOpen(run.runId)}>Open read-only snapshot</button></td></tr>)}</tbody></table></div>}
    {selected && <section className="saved-review" aria-labelledby="saved-review-title"><p className="warning"><strong>Historical saved snapshot.</strong> This is not the current or live analysis. Opening it did not replace current unsaved inputs.</p><div className="panel-heading"><h3 id="saved-review-title">Saved run {selected.runId}</h3><button type="button" onClick={() => downloadSavedRun(selected)}>Export complete JSON</button></div><dl className="summary"><div><dt>Saved</dt><dd>{selected.createdAt}</dd></div><div><dt>Generated</dt><dd>{selected.generatedAt}</dd></div><div><dt>Analysis date</dt><dd>{selected.analysisInputs.fixturePack.fixtureDate}</dd></div><div><dt>Model</dt><dd>{selected.modelVersion}</dd></div></dl><p>{SETTLEMENT_STATEMENT}</p><p>{RESPONSIBLE}</p><h4>Saved candidates</h4>{selected.candidates.length ? selected.candidates.map(candidate => <article className="candidate-card" key={candidate.id}><h5>{candidate.homeTeam} v {candidate.awayTeam}: {candidate.selectionLabel}</h5><p>{candidate.estimatedProbability}% · {candidate.confidence} · {candidate.dataQuality}</p><p>{candidate.reasonsFor.join(' ')}</p><p>{candidate.reasonsAgainst.join(' ')}</p><p>Correlation: {candidate.correlation.relationships.join('; ') || 'No candidate-level relationship noted.'}</p><ul>{candidate.supportingEvidence.sourceIds.map(id => { const source = selected.analysisInputs.researchPack.sources.find(item => item.sourceId === id); return <li key={id}>{source ? <a href={source.url} target="_blank" rel="noreferrer">{source.title}</a> : id}</li> })}</ul></article>) : <p>No saved candidates.</p>}<div className="builders">{builder('High-probability builder', 'high_probability', selected.builders.highProbability)}{builder('Balanced builder', 'balanced', selected.builders.balanced)}</div><p>{SETTLEMENT_STATEMENT}</p><p>{RESPONSIBLE}</p></section>}
  </section>
}
